### ISSUE TITLE
websocket.go imports configs from old repo in edgexfoundry-holding

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-ui-go#109]
Looks like the old repo in holdings still exists and is being reference from the following line.
https://github.com/edgexfoundry/edgex-ui-go/blob/331ddd47aa38a6066cfdee8f1455be93b20338f0/app/component/websocket.go#L24

**Comment by badboy-huaqiao** [comment]
@lenny-intel Thanks,  i just fixed it. see PR-#117
