### ISSUE TITLE
mongo.go init var problem

### ISSUE THREAD

**Issue by broadwit** [edgexfoundry/edgex-ui-go#113]
var (
	database      = configs.DBConf.Name
	dbHost        = configs.DBConf.Host
	dbPort        = configs.DBConf.Port
	dbUserName    = configs.DBConf.Username
	dbPassword    = configs.DBConf.Password
	gatewayScheme = configs.DBConf.Scheme.Gateway
	userScheme    = configs.DBConf.Scheme.User
)

Code above can't initialize the vars.My go version is go1.12.4 linux/amd64.

**Comment by badboy-huaqiao** [comment]
@broadwit it will be better to fix this bug if post your error log

**Comment by badboy-huaqiao** [comment]
we will give up to using mongo as a persistence, so I close it now
