### ISSUE TITLE
broken builds  edgex-ui-go

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-ui-go#114]
We're seeing broken builds in the edgex-ui-go.
during the execution of the Docker build.. we see the following error
00:02:56.111 cp: cannot stat ‘cmd/edgex-ui-go/edgex-ui-go’: No such file or directory

**Comment by TiejunChina** [comment]
@jamesrgregg 
But I cannot see this on my side.

tiejunc@tiejunc-Linux:~/workspace/edgex/src/github.com/edgexfoundry$ git clone git@github.com:edgexfoundry/edgex-ui-go.git
Cloning into 'edgex-ui-go'...
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 1349 (delta 73), reused 111 (delta 60), pack-reused 1210
Receiving objects: 100% (1349/1349), 2.64 MiB | 2.88 MiB/s, done.
Resolving deltas: 100% (709/709), done.
tiejunc@tiejunc-Linux:~/workspace/edgex/src/github.com/edgexfoundry$ cd edgex-ui-go/
tiejunc@tiejunc-Linux:~/workspace/edgex/src/github.com/edgexfoundry/edgex-ui-go$ git checkout edinburgh 
Branch 'edinburgh' set up to track remote branch 'edinburgh' from 'origin'.
Switched to a new branch 'edinburgh'
tiejunc@tiejunc-Linux:~/workspace/edgex/src/github.com/edgexfoundry/edgex-ui-go$ make build
CGO_ENABLED=0 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/edgex-ui-go.Version=0.2.0" -o cmd/edgex-ui-server/edgex-ui-server ./cmd/edgex-ui-server
go: finding github.com/gorilla/mux v1.7.1
go: finding github.com/eclipse/paho.mqtt.golang v1.2.0
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/edgexfoundry-holding/edgex-ui-go v0.0.0-20180906134255-7e731c6fb838
go: finding golang.org/x/net v0.0.0-20190419010253-1f3472d942ba
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: downloading github.com/gorilla/websocket v1.4.0
go: downloading github.com/edgexfoundry-holding/edgex-ui-go v0.0.0-20180906134255-7e731c6fb838
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: extracting github.com/gorilla/websocket v1.4.0
go: downloading github.com/gorilla/mux v1.7.1
go: extracting github.com/eclipse/paho.mqtt.golang v1.2.0
go: extracting github.com/gorilla/mux v1.7.1
go: downloading golang.org/x/net v0.0.0-20190419010253-1f3472d942ba
go: extracting github.com/edgexfoundry-holding/edgex-ui-go v0.0.0-20180906134255-7e731c6fb838
go: extracting golang.org/x/net v0.0.0-20190419010253-1f3472d942ba
CGO_ENABLED=0 GO111MODULE=on go build ./...
tiejunc@tiejunc-Linux:~/workspace/edgex/src/github.com/edgexfoundry/edgex-ui-go$ sudo make docker
[sudo] password for tiejunc: 
docker build --label "git_sha=5942a5919b84b6304aa157f8c0f3231a436edf31" -t edgexfoundry/docker-edgex-ui-go:0.2.0 .
Sending build context to Docker daemon  20.98MB
Step 1/17 : FROM golang:1.11-alpine AS builder
 ---> 6655e91e076d
Step 2/17 : MAINTAINER huaqiao zhang <huaqiaoz@vmware.com>
 ---> Running in b58caaa16b9d
Removing intermediate container b58caaa16b9d
 ---> c5d5872396aa
Step 3/17 : WORKDIR /go/src/github.com/edgexfoundry/edgex-ui-go
 ---> Running in 3d705b8b2466
Removing intermediate container 3d705b8b2466
 ---> 42de55fc1f0c
Step 4/17 : RUN cp /etc/apk/repositories /etc/apk/repositories.bak
 ---> Running in 3683f51c424e
Removing intermediate container 3683f51c424e
 ---> e3c40ab1f7d8
Step 5/17 : RUN echo "https://mirrors.ustc.edu.cn/alpine/v3.6/main" > /etc/apk/repositories
 ---> Running in a3a68921da89
Removing intermediate container a3a68921da89
 ---> ef3ddf4e7016
Step 6/17 : RUN echo "https://mirrors.ustc.edu.cn/alpine/v3.6/community" >> /etc/apk/repositories
 ---> Running in d00f2aecaf30
Removing intermediate container d00f2aecaf30
 ---> 6318bab5cdf4
Step 7/17 : RUN cat /etc/apk/repositories
 ---> Running in 19f313921398
https://mirrors.ustc.edu.cn/alpine/v3.6/main
https://mirrors.ustc.edu.cn/alpine/v3.6/community
Removing intermediate container 19f313921398
 ---> 3929a1b63f27
Step 8/17 : RUN apk update && apk add git make
 ---> Running in 1fa6e95efbe6
fetch https://mirrors.ustc.edu.cn/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.ustc.edu.cn/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.5-44-gda55e27396 [https://mirrors.ustc.edu.cn/alpine/v3.6/main]
v3.6.5-34-gf0ba0b43d5 [https://mirrors.ustc.edu.cn/alpine/v3.6/community]
OK: 8457 distinct packages available
(1/8) Installing libressl2.5-libcrypto (2.5.5-r2)
(2/8) Installing libssh2 (1.8.2-r0)
(3/8) Installing libressl2.5-libssl (2.5.5-r2)
(4/8) Installing libcurl (7.61.1-r2)
(5/8) Installing expat (2.2.0-r1)
(6/8) Installing pcre (8.41-r0)
(7/8) Installing git (2.13.7-r2)
(8/8) Installing make (4.2.1-r0)
Executing busybox-1.29.3-r10.trigger
OK: 29 MiB in 23 packages
Removing intermediate container 1fa6e95efbe6
 ---> 47e7f8130f1d
Step 9/17 : COPY . .
 ---> f95359ceaf35
Step 10/17 : RUN make prepare
 ---> Running in 76c0a462983a
make: Nothing to be done for 'prepare'.
Removing intermediate container 76c0a462983a
 ---> 2f012c2f3fa6
Step 11/17 : RUN make cmd/edgex-ui-server/edgex-ui-server
 ---> Running in e61d7329d004
CGO_ENABLED=0 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/edgex-ui-go.Version=0.2.0" -o cmd/edgex-ui-server/edgex-ui-server ./cmd/edgex-ui-server
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/eclipse/paho.mqtt.golang v1.2.0
go: finding github.com/edgexfoundry-holding/edgex-ui-go v0.0.0-20180906134255-7e731c6fb838
go: finding github.com/gorilla/mux v1.7.1
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/gorilla/websocket v1.4.0
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding gopkg.in/mgo.v2 v2.0.0-20180705113604-9856a29383ce
go: finding golang.org/x/net v0.0.0-20190419010253-1f3472d942ba
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/text v0.3.0
go: finding github.com/kr/text v0.1.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding github.com/kr/pty v1.1.1
go: downloading github.com/edgexfoundry-holding/edgex-ui-go v0.0.0-20180906134255-7e731c6fb838
go: downloading gopkg.in/mgo.v2 v2.0.0-20180705113604-9856a29383ce
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/gorilla/websocket v1.4.0
go: downloading github.com/gorilla/mux v1.7.1
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading golang.org/x/net v0.0.0-20190419010253-1f3472d942ba
Removing intermediate container e61d7329d004
 ---> 9d25874bf443
Step 12/17 : FROM alpine:3.6
3.6: Pulling from library/alpine
5a3ea8efae5d: Pull complete 
Digest: sha256:66790a2b79e1ea3e1dabac43990c54aca5d1ddf268d9a5a0285e4167c8b24475
Status: Downloaded newer image for alpine:3.6
 ---> 43773d1dba76
Step 13/17 : EXPOSE 4000
 ---> Running in cc3b6992b666
Removing intermediate container cc3b6992b666
 ---> 67bff7a101d6
Step 14/17 : COPY --from=builder /go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server /go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server
 ---> 01624617cd72
Step 15/17 : WORKDIR /go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server
 ---> Running in df9e0c7a16b8
Removing intermediate container df9e0c7a16b8
 ---> fab50d6401e6
Step 16/17 : ENTRYPOINT ["./edgex-ui-server"]
 ---> Running in 567be815112a
Removing intermediate container 567be815112a
 ---> 515c0ad475e3
Step 17/17 : LABEL git_sha=5942a5919b84b6304aa157f8c0f3231a436edf31
 ---> Running in 84cfc0b4bfe1
Removing intermediate container 84cfc0b4bfe1
 ---> 189b8093c76c
Successfully built 189b8093c76c
Successfully tagged edgexfoundry/docker-edgex-ui-go:0.2.0
tiejunc@tiejunc-Linux:~/workspace/edgex/src/github.com/edgexfoundry/edgex-ui-go$

**Comment by badboy-huaqiao** [comment]
@jamesrgregg it works well using `make docker` or` docker build . -t` , i did't see this error.

**Comment by lranjbar** [comment]
Issue is stale
