### ISSUE TITLE
[doc] gateway ip address configuration

### ISSUE THREAD

**Issue by giraldeau** [edgexfoundry/edgex-ui-go#124]
That might be obvious, but I'm new to EdgeX and I can't make the edgex-ui-go connect to the gateway (Using docker-compose-edinburgh-1.0.0.yml).

In the `Add Gateway` panel, I tried the following hostnames for the gateway IP:
* `edgex-core-data`: fails
* `edgex-core-command`: fails
* `edgex-proxy`: fails

All services are reported healthy. The internal DNS works and these hostnames are reachable from the `edgex-ui-go` container. Example:

```
$ docker exec -it edgex-ui-go ping -c 1 edgex-core-command
PING edgex-core-command (172.21.0.15): 56 data bytes
64 bytes from 172.21.0.15: seq=0 ttl=64 time=0.083 ms
```

I searched the official EdgeX documentation and couldn't find info about this aspect.

That seems a dumb question, but I just cannot figure out what IP it expects to connect to. I can add it to the wiki if there is a solution.

Thanks!

**Comment by badboy-huaqiao** [comment]
@giraldeau If you run all the micro services by container , the gateway ip should be the ip of host where docker daemon running , neither 'localhost' nor '127.0.0.1'.

i know it's confusing. the EdgeX-ui-go was designed to manage multiple instances of edgexfoundry (let's agree on an instance of edgexfoundry is a gateway), so edgex-ui-go can run anywhere (of course the network to edgexfoundry can reach).

in the further, i will refactor the edgex-ui-go for managing one single instance of edgexfoundry.

**Comment by badboy-huaqiao** [comment]
it's done
