### ISSUE TITLE
Mongodb Connect init 

### ISSUE THREAD

**Issue by plejik** [edgexfoundry/edgex-ui-go#126]
Hey
I try to connect to mongodb 4.0 and give proper user host and password for it but still it failed every time. I could ping host, i try use ip and dns name in config and still no luck.
I could connect with cred by myself but not from edgex-ui-go 
Thx

**Comment by badboy-huaqiao** [comment]
@plejik hi, could you post your configuration here ? the EdgeX-ui-go uses memory db if no config mongo db.  if you want to use mongo, you can refer [https://github.com/edgexfoundry/edgex-ui-go/blob/master/docs/deployments/initmongo.js](url) , or if want to use edgex-mongo server, you should create a table named edgex-ui-go with cred as same as in your configuration [https://github.com/edgexfoundry/edgex-ui-go/blob/master/cmd/edgex-ui-server/res/configuration.toml](url)

**Comment by plejik** [comment]
`[Database]
Host = "192.168.50.4"
Name = "edgex-ui-go"
Port = 27017
Username = "su"
Password = "su"
  [Database.Scheme]
  User = "user"
  Gateway = "gateway"`

`db=db.getSiblingDB("edgex-ui-go");
db.createUser({ user : "su",
    pwd: "su",
    roles: [
      {
        role: "readWrite",
        db: "edgex-ui-go"
      }
    ]
  });
db.createCollection("user");
db.createCollection("gateway");
ts = Date.now();
db.user.insertOne({
    name: "admin",
    password: "admin",
    created: ts,
    modified: ts
  });
` 
Code was integrated to edgex mongodb init script, i could connect to it with out any problem.
I have checked go code and looks like it take config only from toml config.
Mount it `/go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server/res/docker/configuration.toml`
I wrote ansible script fot edgeX HA and this only one service i could not run with store oin mongo db

**Comment by plejik** [comment]
Also if someone could add more verbose output in 
`edgex-ui-go/app/repository/mongo/mongo.go` 
at this point 
```
s, err := mgo.DialWithInfo(mongoDBDialInfo)
	if err != nil {
		log.Println("Connect to mongoDB failed !")
		return false
	}
```
Cause i could not get the error what i have here =( maybe some DEBUG env vars or in config

**Comment by badboy-huaqiao** [comment]
@plejik i think there is some of the confusion  i have explained at issue-#124 ,please move to [https://github.com/edgexfoundry/edgex-ui-go/issues/124#issuecomment-519412869](url)

**Comment by plejik** [comment]
I have to check it but currently i have mongo on separate instance =\

**Comment by badboy-huaqiao** [comment]
it' done ,
