### ISSUE TITLE
Device service returns status 200 with empty content as fails

### ISSUE THREAD

**Issue by samhsu427** [edgexfoundry/edgex-ui-go#129]
If device service returns status 200 with empty body and a JSON Content-Type then it fails and we have to rely on dataType: 'text'. 
https://github.com/edgexfoundry/edgex-ui-go/blob/348ff9621e1a729d83a88529a614ad4c673af466/web/static/js/pages/devices/device.js#L258-L262

**Comment by badboy-huaqiao** [comment]
I close it, because it had been fixed
