### ISSUE TITLE
Impossible to change edgex-ui-go 

### ISSUE THREAD

**Issue by wassim6975** [edgexfoundry/edgex-ui-go#134]
Hi everyone, i was trying to change edgex-ui-go, but i could not see my changes because changing the files in edgex-ui-go does not change anything. Still, I also test my changes in separate files and it worked ...
How can I change edgex-ui-go to see my changes?
(I am trying to change the html file and js of multimedia to display a graph of the values of my devices)
Thank you in advance for your help

**Comment by badboy-huaqiao** [comment]
@wassim6975 clean browser cache after re-codec html or js file,  or  open and use developer mode (like Chrome browser: developer tool -> network -> checked Disable cache), keep this section open.
![image](https://user-images.githubusercontent.com/16172215/68265405-e40e9500-0086-11ea-812f-417ebc044140.png)

**Comment by wassim6975** [comment]
@badboy-huaqiao Thank you for your answer. 
I could solve my problem.
