### ISSUE TITLE
使用ui添加设备成功，可以上传数据，但是send get和set 都不成功

### ISSUE THREAD

**Issue by liyuAndzww** [edgexfoundry/edgex-ui-go#144]
我这边通过按照官网中的教程，添加好“Test.Device.MQTT.Profile”设备后，直接在该平台上通过UI来添加自定义的设备。UI上添加成功后，自定义的服务也可以上抛数据到core data，但是command中的get和set一直都不成功。
![image](https://user-images.githubusercontent.com/25681809/75238435-f5c5a500-57fb-11ea-920c-ae49b100ffac.png)

我这边的各类配置如下，设备的yaml文件，camera.yaml，因为一直都没成功，我这边目前为了验证问题，目前实际上就直接拿的官网模板中的testmessage的部分
![image](https://user-images.githubusercontent.com/25681809/75234986-8ac59f80-57f6-11ea-84a3-dc07308fb679.png)

UI中配置
![image](https://user-images.githubusercontent.com/25681809/75237642-aaf75d80-57fa-11ea-974b-6d5e510ca105.png)
![image](https://user-images.githubusercontent.com/25681809/75237675-b8144c80-57fa-11ea-9275-5e7671a0020c.png)

docker-compose.yml中mqtt的设定和教程一样，未修改
![image](https://user-images.githubusercontent.com/25681809/75236045-302d4300-57f8-11ea-9734-26eb4c062fd9.png)

点击教程中添加的设备命令的send按钮
![image](https://user-images.githubusercontent.com/25681809/75238008-51dbf980-57fb-11ea-9879-97f2fb097578.png)

终端输入  mosquitto_sub -v -t '#'来查看broker 中的信息，可以看到这个时候已经有
![image](https://user-images.githubusercontent.com/25681809/75238152-7e901100-57fb-11ea-877a-ad647ccf7496.png)
但是我点击我添加设备中的send，却没有看到有thisisatest的topic出来，我的理解无论我设备对应的微服务是否有问题，这里的下来的thisisatest应该是都要有的。把这里的thisisatest换成CommandTopic也是一样

**Comment by liyuAndzww** [comment]
我这边通过命令来查看
![image](https://user-images.githubusercontent.com/25681809/75239507-c6179c80-57fd-11ea-835c-93ef19a1d0fd.png)
可以看到设备命令，但是在postman上去get地址http://172.17.0.1:48082/api/v1/device/name/camera/command/testmessage
报如下错误（不需要注意名称，因为我这边修改了多次）
Handler - execReadCmd: error for Device: intelligent_camera cmd: faceinfo, unable to load config, 'mqtt' not exist /api/v1/device/d5fe17c4-2b7c-48fd-a77b-2d594dd59487/faceinfo

**Comment by DaveZLB** [comment]
您好，这可能是由于您在添加device时，DeviceAddressable 参数不对导致的，下面图片中，第一列的参数指的是协议类型，这个值是固定的，如果您使用mqtt协议的话，值就是mqtt;
<img width="803" alt="WeChatc17d482d0b173d50fc0646b808b9903a" src="https://user-images.githubusercontent.com/29951254/75410707-b90ec080-5957-11ea-9f2b-6fddf2c4aa52.png">

此处的设计还有待改进

**Comment by DaveZLB** [comment]
这里是fuji版本的添加mqtt设备到EdgeX
https://github.com/edgexfoundry/edgex-docs/blob/fuji/examples/Ch-ExamplesAddingMQTTDevice.rst

**Comment by DaveZLB** [comment]
this issue may be closed, @badboy-huaqiao , those who try to use EdgexUI can pull master branch for test, new features are showed belowed
<img width="813" alt="WeChat3d8e2be7bb3a6c82c5d7840179593d72" src="https://user-images.githubusercontent.com/29951254/76511865-b3a09280-648e-11ea-89d1-5a4d32a6cb19.png">

**Comment by badboy-huaqiao** [comment]
@DaveZLB if you had fixed it , I will close it
