### ISSUE TITLE
Change form submit  to ajax way when upload device profile

### ISSUE THREAD

**Issue by DaveZLB** [edgexfoundry/edgex-ui-go#163]
The reason is that  upload result is not rendered properly. 
eg. statusCode : 409 , responseMessage:Duplicate profile name

**Comment by badboy-huaqiao** [comment]
@DaveZLB We're moving towards the H5 standard, but not too aggressively, when I choose one new tech, I will look at how widely it supports major browsers, so ,please be sure to test all major browsers for support, especially IE. 
But if you have tested it and made sure it works well, I will merge the PR-#164

**Comment by DaveZLB** [comment]
@badboy-huaqiao ，I have tested this function part  in Chrome ,Firefox, safari and Microsoft Edge for mac(Chromium kernel), it's ok.

**Comment by badboy-huaqiao** [comment]
@DaveZLB Ok, it's done

**Comment by DaveZLB** [comment]
done
