### ISSUE TITLE
Update scheduler service to match edgexfoundry

### ISSUE THREAD

**Issue by badboy-huaqiao** [edgexfoundry/edgex-ui-go#168]
The main updates are as follows:

1：keep the term 'scheduler' unchanged in the menu
2: Inside the scheduler page, change term 'scheduler' to 'interval', change term 'scheduler event' to 'interval action'

3：(optional) Redesign to replace the current form-only approach with friendly way

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/16172215/76727943-52c7d180-6790-11ea-85c1-a6825d46cd7f.png">

**Comment by badboy-huaqiao** [comment]
@wshengqi @DaveZLB if anything not clear, please communicate with me

**Comment by DaveZLB** [comment]
New features for interval part in schedule page are shown below,
<img width="1223" alt="WeChat2ef06bc9c43338610c877f70f7ad1ae6" src="https://user-images.githubusercontent.com/29951254/77031848-c6125300-69dd-11ea-83e0-be70bdba1e1a.png">

**Comment by DaveZLB** [comment]
New changes for interval action in schedule page are shown below

<img width="1219" alt="intervalaction2" src="https://user-images.githubusercontent.com/29951254/77716483-460d6e00-7019-11ea-9409-d6bec4a05950.png">
<img width="1212" alt="intervalaction1" src="https://user-images.githubusercontent.com/29951254/77716490-486fc800-7019-11ea-9628-61d17e309a90.png">

**Comment by DaveZLB** [comment]
This issue has been finished

**Comment by badboy-huaqiao** [comment]
ok, good, I close it now
