### ISSUE TITLE
Add css style for all buttons of  deviceservice,device and command  list

### ISSUE THREAD

**Issue by badboy-huaqiao** [edgexfoundry/edgex-ui-go#177]
@DaveZLB 
As follow:
some button without css style, I recommend adding a green style to keep up with the rest

<img width="388" alt="image" src="https://user-images.githubusercontent.com/16172215/77992829-7165c500-7359-11ea-8b37-32912a8eb4b8.png">

**Comment by DaveZLB** [comment]
ok

**Comment by DaveZLB** [comment]
done
