### ISSUE TITLE
Improve command list layout

### ISSUE THREAD

**Issue by badboy-huaqiao** [edgexfoundry/edgex-ui-go#20]
Improve command list layout, so far , the layout of command is unreasonable, users from community are very sensitive to this issue , please complete it as soon as possible , thanks, :-) @yanghua

**Comment by badboy-huaqiao** [comment]
用户对这个问题很在意，现在命令行的布局不是很合理，参数变多的情况下，单元格被撑破，急需重新布局，请尽快完成，谢谢 ：-） @yanghua

**Comment by DaveZLB** [comment]
ok

**Comment by badboy-huaqiao** [comment]
move to issue #275 , it's done!
