### ISSUE TITLE
Validate corresponding service alive or running before send request

### ISSUE THREAD

**Issue by badboy-huaqiao** [edgexfoundry/edgex-ui-go#201]
We should add some mechanism to confirm corresponding edgex service alive or running to improve user experience

**Comment by DaveZLB** [comment]
the details see #204

**Comment by DaveZLB** [comment]
the feature has done @badboy-huaqiao

**Comment by badboy-huaqiao** [comment]
@DaveZLB ok, close it now.

**Comment by badboy-huaqiao** [comment]
Though this issue has some replicate stuff with issue #199, but I reopen this one to refactor it from backend

**Comment by badboy-huaqiao** [comment]
it belongs to old UI, I removed the features mentioned above because of received a lot of bad feedback from the users who is confused with that red and green dot in front of each one menu items.

it's a bad design for user interface！so removed that features!
