### ISSUE TITLE
发现ui 在接入设备后执行命令有问题。

### ISSUE THREAD

**Issue by golangpkg** [edgexfoundry/edgex-ui-go#208]
deviceService.js line ： 

cmdUrl = cmdUrl.replace(/(\w+):\/\/([^/:]+)(:\d*)?/,"/core-command");// 没有替换成功
cmdUrl = cmdUrl.replace(/(\w+):\/\/(:\d*)?/,"/core-command");

有些服务注册的时候，没写IP，可以对外，这样没有映射 IP 地址 还得再替换下没有IP 的情况。

比如会出现： 

http://:48082/api/v1/device/

**Comment by badboy-huaqiao** [comment]
@golangpkg 你是用源码跑的edgexfoundry吗？

**Comment by DaveZLB** [comment]
@golangpkg，这个是您在使用ui的时候出现的一个bug么，具体bug是什么，您描述的情况确实有可能出现，如果gateway页面没有填ip的话，这时候会出现http://:48082/api/v1/device/这种情况，但是在后台做反向代理的时候http://:48082/api/v1/device/会被默认解析成http://localhost:48082/api/v1/device/,是不会报错的，也不会影响正常使用，如果是这种情况的话，我们可以调整一下代码，也欢迎您提pr,最近master做了用户友好性改动，建议您可以试一下。

**Comment by badboy-huaqiao** [comment]
@golangpkg Has your trouble solved? if you have fixed it , please post your solution, then I will close this issue, thanks
