### ISSUE TITLE
EdgeX Foundry UI Console中接收不到device  ReadValue的返回值

### ISSUE THREAD

**Issue by limeihui1127** [edgexfoundry/edgex-ui-go#209]
可以在mqtt端接受到send来的消息，但是readvalue的值是failed。docker logs edgex-device-mqtt后显示如下

<img width="779" alt="image" src="https://user-images.githubusercontent.com/26920939/79423125-a0826480-7ff0-11ea-8e13-4beb79c9a25d.png">

**Comment by DaveZLB** [comment]
您使用的ui版本是fuji版本，还是master分支，按照我的经验，这个问题可能出在edgex-device-mqtt这个微服务上，您可以在启动整个edgex服务后，重新docker restart  edgex-device-mqtt试试

**Comment by badboy-huaqiao** [comment]
@limeihui1127 原因是broker的响应时间过长，而device-mqtt微服务硬编码设置了超时5s后就报错，本人实测：超过4s就会报错，请遇到此类问题的小伙伴，确保自己的broker响应时间在4s以内。

或者修改device-mqtt微服务源码的超时时长，在driver.go文件中如下代码块修改：
<img width="762" alt="image" src="https://user-images.githubusercontent.com/16172215/79436892-0a583980-8004-11ea-8990-07c36854a010.png">

**Comment by badboy-huaqiao** [comment]
@limeihui1127 用户反馈此问题经过上述方式后，已经解决，我关闭这个issue，如果有类似问题，可以引用此issue。

@DaveZLB 可以考虑如何重新设计command list ，给予友好提示，现在只是简单的显示failed

**Comment by DaveZLB** [comment]
ok
