### ISSUE TITLE
Redesign deviceProfile from uploading way to ui config way

### ISSUE THREAD

**Issue by DaveZLB** [edgexfoundry/edgex-ui-go#210]
1> Design deviceProfile page(css,html)
2> Use angularjs for data template and data binding

1 week

**Comment by badboy-huaqiao** [comment]
it belongs to old UI, move to issue #275 , in the new UI we provides a new feature of web editor which gives the ability of user to edit the profile online to improve user experience, see below screenshot:

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/16172215/121640677-cefab300-cac0-11eb-8bd5-6525637ff549.png">
