### ISSUE TITLE
Refactor part code for better code maintenance and higher coding efficiency

### ISSUE THREAD

**Issue by DaveZLB** [edgexfoundry/edgex-ui-go#211]

**Comment by DaveZLB** [comment]
1> using front-end architecture  instead of jquery, such as AngularJS

**Comment by badboy-huaqiao** [comment]
@DaveZLB firstly , jquery is not a front-end architecture, secondly , angularjs is not supported officially any more, but angular2+ would be considered, but after research, there're some stuff cannot be overcome, such as data communication bidirectional must rely on backend server which angular2 cannot reach, others like layout, one page may consist of multiple components, but in angular2+ model, one component is consists of three subcomponent at least, it' looks not so convenient for developer, and the most point is that angualr2+ is just a web-end architecture,  it doesn't officially provide a complete component library of its own ,which means that yourself only can rely on third part library, and you or me or the community developers don't have ability to develop one. so it should be as second option.

**Comment by badboy-huaqiao** [comment]
这里补充一下，根据edgex官方要求，UI会一点点接近产品版本，技术选型进行重构，个人从社区贡献code以及团队开发人员等方面考虑，进行投票技术选型，可用方案如下：
1：go template
2：angular2+
3：vue
4：react

**Comment by 16301094** [comment]
站一票vue吧，轻量级，能够快速开发迭代。
