### ISSUE TITLE
Build failure "bar" executable file not found

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-ui-go#217]
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /Users/mbhandaru/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: error loading module requirements

**Comment by badboy-huaqiao** [comment]
@mkbhanda I met the same stuff as you,  but I have fixed it, see issue-#194, can you post Jenkins's error log

**Comment by mkbhanda** [comment]
I think my mistake, I used fuji and should have used latest greatest from git as opposed to fuji container
Please close

**Comment by badboy-huaqiao** [comment]
@mkbhanda 👍，it's ok😊, thanks, I close it now
