### ISSUE TITLE
A duplicate user problem was encountered using edgex-ui-go

### ISSUE THREAD

**Issue by tingtlu** [edgexfoundry/edgex-ui-go#235]
When entering the registration page for the first time, no matter what username is used during registration, an error is displayed: Duplicate user: xxx
![image](https://user-images.githubusercontent.com/46401850/84136639-2b765d00-aa7e-11ea-8496-3407f61f461e.png)

**Comment by DaveZLB** [comment]
you can try to  restart edgex-ui container

**Comment by tingtlu** [comment]
重启不行，我已经试过卸载后再安装运行，问题如初。关键一点是：无论注册什么用户名，都是显示这个错误！

**Comment by badboy-huaqiao** [comment]
@tingtlu 哪个版本的image？@wshengqi @DaveZLB 拉取验证一下

**Comment by tingtlu** [comment]
我用的是源码编译版本的（即：使用make build编译，make run启动运行），不是用的容器版

**Comment by badboy-huaqiao** [comment]
@tingtlu ok,  @DaveZLB @wshengqi 他应该用的是master主分支的源码编译跑的，验证一下现在源码是否有该问题

**Comment by tingtlu** [comment]
我又试了一下，直接在主机中run编译后的程序，就会出现上述问题。但利用Dockerfile 文件构建镜像，运行容器后，这个问题就没有了，但是又出现另外一个问题：利用注册的账号，在登陆页面点击之后没有反应, 然后修改URL为：http://目标主机ip:4000（也就是删除端口号之后的路径信息）,就可以进入主页面，但随便点击页面中的任何按钮，就会回到登陆界面。

**Comment by DaveZLB** [comment]
您可以先用这个docker ui版本试一下，https://github.com/edgexfoundry/developer-scripts/blob/master/releases/geneva/compose-files/docker-compose-geneva-ui.yml，创建用户，登录成功后，要在gateway page 新增一个127.0.0.1的配置，应该就都正常了。EdgeX docker版本可以是fuji或者Geneva。
我正在检查您说的这个问题。

**Comment by DaveZLB** [comment]
@tingtlu , 我进行了以下测试在本机，EdgeX 版本为[Geneva](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/geneva/compose-files/docker-compose-geneva-redis-no-secty.yml)
1> 在本地编译运行
`make build
 make run
`
2> 使用docker镜像运行
`make docker
docker run --network=compose-files_edgex-network  -p 4000:4000   edgexfoundry/docker-edgex-ui-go:0.0.0
`
访问http://localhost:4000
使用的浏览器为Chrome 和Firefox，没有发现您描述的问题。您可以在清空一下浏览器缓存试一试

**Comment by tingtlu** [comment]
@DaveZLB ，我用的版本是california版，浏览器使用Chrome ，清空缓存后编译在主机运行的还是有这个问题，docker镜像（源码编译后的）的没有这个问题了，但主页上没有gateway选项：
![image](https://user-images.githubusercontent.com/46401850/84218781-b5b3d500-ab01-11ea-99ee-7e7695d70bb2.png)
另外说明一下，根据我主机ip我修改了Datebase的地址，以及注释掉mm.DBConnect()，启用：mongo.DBConnect()：
![image](https://user-images.githubusercontent.com/46401850/84218983-28bd4b80-ab02-11ea-8166-eff9d3848747.png)
![image](https://user-images.githubusercontent.com/46401850/84219127-64f0ac00-ab02-11ea-83c9-c3c7092a9fb8.png)
最后，我还是使用california版，配上https://github.com/edgexfoundry/developer-scripts/blob/master/releases/geneva/compose-files/docker-compose-geneva-ui.yml这个镜像，UI可以正常运行了。

**Comment by DaveZLB** [comment]
@tingtlu , [EdgeX](https://github.com/edgexfoundry/edgex-go)的版本是这样的california->delhi->edinburgh->fuji->master(Geneva),您用的版本太老了，目前UI master分支的只是对fuji或者geneva做了适配，如果您使用california版本的话，只能使用对应的ui镜像版本,UI的分支也是从delhi版本开始的适配。建议您尝试使用fuji版本或者Geneva版本，对应的版本您可以从[这里](https://github.com/edgexfoundry/developer-scripts/tree/master/releases)获取到。执行对应的docker-compose就可以了，docker-compose选no-secty后缀，表示edgex不启动安全组件。
另外，如您截图所示，如果出现红色小点代表ui和edgex没有连接成功。如果连接成功，画面应该是这样的。
<img width="1428" alt="WeChatf08496b2cff56994c87c2ebf0856e243" src="https://user-images.githubusercontent.com/29951254/84220287-01b44900-ab05-11ea-8e60-6039f23dcd88.png">

**Comment by DaveZLB** [comment]
@tingtlu ,应该不需要修改任何代码或者配置，另外目前ui没有完整的用户管理，这一块并不完善，下一版本会将用户创建以及登录也去掉，ui目前的定位是dev和test.

**Comment by tingtlu** [comment]
@DaveZLB 嗯，明白，谢谢！

**Comment by badboy-huaqiao** [comment]
@tingtlu ok，it seems to have been solved, I close it now, if any other questions related to this issue, I will reopen it.
