### ISSUE TITLE
MQTT设备微服务连接模拟设备问题

### ISSUE THREAD

**Issue by wanght3w** [edgexfoundry/edgex-ui-go#244]
按照huaqiao的视频来测试MQTT设备微服务连接虚拟设备，模拟虚拟设备的代码就是从他的github下载的，然后设备也注册好了，mqttbroker也起来了
![image](https://user-images.githubusercontent.com/64407741/85117601-af380280-b251-11ea-91ee-7d11a2a78dfe.png)

，运行那个模拟设备的python代码，显示这样
![image](https://user-images.githubusercontent.com/64407741/85117653-c4149600-b251-11ea-8c44-c9cc77ee8a31.png)
然后ui那边点send过了一会都返回failed，显示这样
![image](https://user-images.githubusercontent.com/64407741/85117708-db538380-b251-11ea-8da5-a6e9128ed962.png)
不知道哪里出了问题，该怎么办呢？

**Comment by DaveZLB** [comment]
@wanght3w ,你可以先参考一下这个issue看能否解决您的问题[https://github.com/edgexfoundry/edgex-ui-go/issues/209](https://github.com/edgexfoundry/edgex-ui-go/issues/209)

**Comment by wanght3w** [comment]
@DaveZLB ，所以是要修改mqtt微服务源码嘛，我是docker-compose pull的镜像运行的，driver.go这个文件在哪找，没找到啊

**Comment by DaveZLB** [comment]
@wanght3w ，您可以先试着在docker重启一下edgex-device-mqtt 服务来解决。

**Comment by wanght3w** [comment]
@DaveZLB， 试过了，没有效果。

**Comment by wanght3w** [comment]
@DaveZLB ，mqtt微服务的日志
![image](https://user-images.githubusercontent.com/64407741/85122391-0b525500-b259-11ea-8bc4-842589eaddcd.png)

**Comment by DaveZLB** [comment]
@wanght3w ,按照您提供的线索，我做了测试，可以正常运行，您可以按照以下步骤完成MQTT device测试。

1. 执行以下代码启动一个mqtt broker
`docker run -d --name broker -p 1883:1883 eclipse-mosquitto`

2. 使用[Geneva docker](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/geneva/compose-files/docker-compose-geneva-redis-no-secty.yml) 版本，将MQTT注释部分打开，启动docker-compose(这个时候edgx-device-mqtt由于默认配置Driver.IncomingHost=0.0.0.0而无法工作,需要在consul修改配置动态生效)。

3.  在浏览器输入http://localhost:8500(consul 注册中心)，在Key / Values >edgex> devices > 1.0
edgex-device-mqtt >  Driver 下找到IncomingHost和ResponseHost修改0.0.0.0为yourhostip. 然后docker  restart重启 edgex-device-mqtt 服务.

4、在UI界面DeviceService page -> Device Profile 上传mqtt deviceProfile,文件内容如下：
`
# mqtt.test.device.profile.yml
name: "Test.Device.MQTT.Profile"
manufacturer: "Dell"
model: "MQTT-2"
labels:
- "test"
description: "Test device profile"
deviceResources:

- name: randfloat32
  description: "device random number with Base64 encoding"
  properties:
    value:
      { type: "Float32", size: "4", readWrite: "R", defaultValue: "0.00", minimum: "100.00", maximum: "0.00", floatEncoding: "Base64" }
    units:
      { type: "String", readWrite: "R", defaultValue: "" }
- name: randfloat64
  description: "device random number with e notion"
  properties:
    value:
      { type: "Float64", size: "4", readWrite: "R", defaultValue: "0.00", minimum: "100.00", maximum: "0.00", floatEncoding: "eNotation" }
    units:
      { type: "String", readWrite: "R", defaultValue: "" }
-
  name: ping
  description: "device awake"
  properties:
    value:
      { type: "String", size: "0", readWrite: "R", defaultValue: "oops" }
    units:
      { type: "String", readWrite: "R", defaultValue: "" }
-
  name: message
  description: "device notification message"
  properties:
    value:
      { type: "String", size: "0", readWrite: "W" ,scale: "", offset: "", base: ""  }
    units:
      { type: "String", readWrite: "R", defaultValue: "" }

deviceCommands:
- name: testrandfloat32
  get:
    - { index: "1", operation: "get", deviceResource: "randfloat32"}
- name: testrandfloat64
  get:
    - { index: "1", operation: "get", deviceResource: "randfloat64"}
-
  name: testping
  get:
    - { index: "1", operation: "get", deviceResource: "ping"}
-
  name: testmessage
  get:
    - { index: "1", operation: "get", deviceResource: "message"}
  set:
    - { index: "1", operation: "set", deviceResource: "message"}

coreCommands:
- name: testrandfloat32
  get:
    path: "/api/v1/device/{deviceId}/testrandfloat32"
    responses:
    -
      code: "200"
      description: "get the random float32 value"
      expectedValues: ["randfloat32"]
    - code: "500"
      description: "internal server error"
      expectedValues: []
- name: testrandfloat64
  get:
    path: "/api/v1/device/{deviceId}/testrandfloat64"
    responses:
      - code: "200"
        description: "get the random float64 value"
        expectedValues: ["randfloat64"]
      - code: "500"
        description: "internal server error"
        expectedValues: []
-
  name: testping
  get:
    path: "/api/v1/device/{deviceId}/testping"
    responses:
    -
      code: "200"
      description: "ping the device"
      expectedValues: ["ping"]
    - code: "500"
      description: "internal server error"
      expectedValues: []
-
  name: testmessage
  get:
    path: "/api/v1/device/{deviceId}/testmessage"
    responses:
    -
      code: "200"
      description: "get the message"
      expectedValues: ["message"]
    - code: "500"
      description: "internal server error"
      expectedValues: []
  put:
    path: "/api/v1/device/{deviceId}/testmessage"
    parameterNames: ["message"]
    responses:
    -
      code: "204"
      description: "set the message."
      expectedValues: []
    - code: "500"
      description: "internal server error"
      expectedValues: []

`
5. 在UI界面DeviceService page -> Devices 添加新的device,如下图：
<img width="1406" alt="WeChat153296f54b2d68945e41886f0b9e5262" src="https://user-images.githubusercontent.com/29951254/85135143-35634180-b270-11ea-8071-934d5766a923.png">

6. 下载[mock-device-for-mqtt.py](https://github.com/badboy-huaqiao/mock-device-driver/blob/master/mock-device-for-mqtt.py) 并运行。

7、在Deviceservice page -> Devices -> Commands 点击Send进行测试。

**Comment by wanght3w** [comment]
@DaveZLB [，好了，send可以收到message了，但是set显示成功了而message并没有改变，那个python脚本里写的testcollect的set也失败（我用的python3，脚本里我就将原来图里红圈的Q改为q，因为报错）
![image](https://user-images.githubusercontent.com/64407741/85198380-d73f6880-b31a-11ea-9838-31a5245e181a.png)
然后通过postman来测试这个set下面报错
![image](https://user-images.githubusercontent.com/64407741/85198481-af043980-b31b-11ea-833e-8f48b41c7d8d.png)

**Comment by DaveZLB** [comment]
@wanght3w ,

> send可以收到message了，但是set显示成功了而message并没有改变

在parameter 列message参数键入的内容是你要发给这个模拟设备mock-device-for-mqtt.py 的，你要在它的log里面看。页面没有渲染展示它返回的内容，这块有待改进。




> 那个python脚本里写的testcollect的set也失败

这个有可能是你的mqtt.test.device.profile.yml关于testcollect部分设置不正确导致的
具体做法参考
https://fuji-docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html

另外要确保下面的参数在consul里面都修改成功
<img width="467" alt="WeChat29671a4aa9b20bd49f9657ca533cc8ea" src="https://user-images.githubusercontent.com/29951254/85199222-626f2d00-b320-11ea-80d1-5bae55bfbfc9.png">

**Comment by wanght3w** [comment]
@DaveZLB ，有这样一个问题，我现在有一个树莓派，我想把这个树莓派当作一个设备连接到edgex上，该怎么办？

**Comment by DaveZLB** [comment]
@wanght3w ，首先您的树莓派上面要有一个程序使用mqtt协议来和edgex-mqtt-device进行通信，通信的协议格式为edgex给定的，最简单的方式是您可以直接将mock-device-for-mqtt.py放到您的树莓派上作为和edgex-mqtt-device通信的程序，您需要修改mock-device-for-mqtt.py里面的通过命令获取的内容或者要执行的动作部分，现在都是模拟数据，比如树莓派可以接温度传感器的数据，修改mock-device-for-mqtt.py，在里面调用获取温度传感器数据的api来作为应答内容。下面红款内的就是您可以修改应答内容的地方。

<img width="647" alt="WeChat5c3a817925fdfdf0293d33f456a6dc96" src="https://user-images.githubusercontent.com/29951254/85241745-74abb100-b46f-11ea-8095-6d7312968bf1.png">

如果您要新增命令，那就要按照之前我给你的链接参考edgex给出的格式。然后在mock-device-for-mqtt.py里面对应的新增接受新命令进行处理的代码。

**Comment by wanght3w** [comment]
@DaveZLB ，哦哦，您看我下面的做法是将树莓派连接到edgex了吗，仍然用模拟数据。将那个python模拟的脚本程序在树莓派上运行（地址改成树莓派的地址了），树莓派上启的broker，
![image](https://user-images.githubusercontent.com/64407741/85218883-247e1180-b3d1-11ea-9246-cb60091fc074.png)
然后再虚拟机edgex上注册设备（地址为树莓派地址），
![image](https://user-images.githubusercontent.com/64407741/85218894-45466700-b3d1-11ea-9e78-12264ffae21f.png)
**但send返回显示failed**，
![image](https://user-images.githubusercontent.com/64407741/85218904-60b17200-b3d1-11ea-9c9d-432c5be15aa6.png)
树莓派终端
![image](https://user-images.githubusercontent.com/64407741/85219062-1c26d600-b3d3-11ea-9695-611feb5ebbad.png)

**Comment by DaveZLB** [comment]
@wanght3w ,这里的broker指的是mqtt server, 它的作用是 edgex-mqtt-device(mqtt message) -> mqttbroker -> yourdevice(mqtt message). broker位于哪都行，只要edgex-mqtt-device和yourdevice都可以通过brokerip:1883连上就可以(确保都是连通的)，但是不倾向于将broker放在yourdevice上。

**Comment by wanght3w** [comment]
@DaveZLB ，哦哦，明白点了，就是我还是在虚拟机（运行edgex）启broker，在consul中已经修改过为虚拟机地址，把那个模拟python脚本（其中的地址还是虚拟机的）放到树莓派运行，就是edgex-mqtt-device(mqtt message)（虚拟机）-> mqttbroker（虚拟机） -> yourdevice(mqtt message)（树莓派）这样。但是树莓派终端运行那个python脚本显示
![image](https://user-images.githubusercontent.com/64407741/85256953-93be3900-b497-11ea-91b5-262a0a142ae8.png)
过一会就显示超时
![image](https://user-images.githubusercontent.com/64407741/85257036-bb150600-b497-11ea-8c78-a1188569979d.png)

**Comment by DaveZLB** [comment]
@wanght3w, 应该是您的两个虚拟机，网络没有打通，或者端口被防火墙墙了，您可以telnet 192.168.238.128 1883, 您描述的mqtt message 流动的方向是对的，关于这块整体的理解还需要参考https://fuji-docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html。
edgex-mqtt-device 相当于 EdgeX与device之间的适配层，它可以连接多个 mqtt device.

**Comment by wanght3w** [comment]
@DaveZLB ，您好，我还想请教一下APPServcie微服务如何使用，通过它将获取的数据向上导出到云。譬如之前mqtt设备微服务获取的设备发送的数据信息，如何通过APPService微服务导出到一个云端呢？
![image](https://user-images.githubusercontent.com/64407741/85918170-e54d3600-b892-11ea-9cba-ce71ed40ba64.png)

**Comment by DaveZLB** [comment]
在Transforms-> Export 选项里面有多种导出方式，比如说HttpExport或者MQTTExport方式，对于HttpExport而言，你需要建立一个Http Server创建一个Post请求的Url，然后拖拽Export里面的方法，编辑对应的参数，然后点击Deploy to Consul. MQTT Export类似.

<img width="1433" alt="WeChat7f3b99673c81498fbe7662b2a82de752" src="https://user-images.githubusercontent.com/29951254/85944200-89a0ac80-b967-11ea-8a3a-22ebd4a0458e.png">

**Comment by wanght3w** [comment]
@DaveZLB ，那如何确定我要导出的数据是什么呢？就以前面那个mqtt设备微服务收到的message(Are you ok)为例，通过HttpExport怎么确定是将那个message(Are you ok)导出到某一个Server呢？或者通过MQTT Export导出到某一个broker？

**Comment by tianxingguo** [comment]
HOST 是mqtt broker 的IP , ClientId = "CommandPublisher",修改后应该work

**Comment by badboy-huaqiao** [comment]
@wanght3w 开发人员的回复是否已经解决了你的问题？另外，关于app service的问题，我看到已经有独立的issue #251 ，请移步到对应的issue讨论
