### ISSUE TITLE
initialize Mongo Err

### ISSUE THREAD

**Issue by gavinju** [edgexfoundry/edgex-ui-go#248]
**My Env is as follows:**
Ubuntu：18.04
Edgex-ui-go：fuji
Mongodb：4.0.18

**My Problem is :** When performing mongo init I get an error.

**The wrong information is:**
MongoDB shell version v3.6.3
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 4.0.18
WARNING: shell and server versions do not match

Please help me, thanks！！！

**Comment by DaveZLB** [comment]
UI Geneva version has been released. it is applicable to EdgeX fuji and Geneva version. you can try it. Or you can download UI master branch and run it.
https://github.com/edgexfoundry/developer-scripts/blob/master/releases/geneva/compose-files/docker-compose-geneva-ui.yml.

**Comment by badboy-huaqiao** [comment]
@gavinju well, Has your problem been solved? If so, I will close the issue

**Comment by gavinju** [comment]
@DaveZLB Thank you for your help.  
If Geneva doesn't need mongo database，Where the user information is stored？

**Comment by DaveZLB** [comment]
@gavinju ,User information is stored in memory  in Geneva version temporarily. It is a compromise solution. 
The user login page will be removed in the next version, so there is no user information, all the data of the UI comes from EdgeX Restful API.

**Comment by badboy-huaqiao** [comment]
I think it's been done, close it now
