### ISSUE TITLE
APPService微服务如何将获取的数据导出到云？

### ISSUE THREAD

**Issue by wanght3w** [edgexfoundry/edgex-ui-go#251]
APPServcie微服务如何使用，通过其将获取的数据向上导出到云。例如，mqtt设备微服务获取的设备发送的数据信息，如何通过APPService微服务导出到一个云端呢？在ui中如何进行？
![image](https://user-images.githubusercontent.com/64407741/85922817-bb0e6f00-b8b8-11ea-91d0-b04199e6f600.png)

**Comment by badboy-huaqiao** [comment]
@wshengqi

**Comment by wanght3w** [comment]
如何确定我要导出的数据是什么呢？就以用程序（mock-device-for-mqtt）模拟设备的那个mqtt设备微服务收到的message(Are you ok)为例，通过HttpExport怎么确定是将那个message(Are you ok)导出到某一个Server呢？或者通过MQTT Export导出到某一个broker？

**Comment by DaveZLB** [comment]
@wanght3w , AppServices 是您从EdgeX导出数据的一种方式，它支持HttpExport和MQTTExport方式，我拿HttpExport导出数据到云端为例，
1> 首先您的云端需要一个接受EdgeX 数据的接口，即一个HttpPost请求，比如您建立了一个接口为http://edgexdatacallback
2> 在AppServices  -> Available Transforms  -> Filtering 里面选则一个Filtering function,如FilterByDeviceName（可以按设备名等过滤，如果不选择的话，默认不滤数据），以过滤要发送到云端的数据，然后在选择一个Export function,如HttpPost. 修改HttpPost 里面的参数，将url 修改为http://edgexdatacallback（EdgeX之后会回调这个接口，给你推送数据）
3> 点击deployToConsul。

![image](https://user-images.githubusercontent.com/29951254/85982712-e019f380-ba18-11ea-9bc1-616fba4c3029.png)


![image](https://user-images.githubusercontent.com/29951254/85982763-f758e100-ba18-11ea-9c07-abf9d2923e53.png)

对于MQTTExport的方式也类似，只不过将HttpPost url 换成了MQTT topic，你需要在云端监听这个topic，EdgeX会向这个topic发送数据。

**Comment by badboy-huaqiao** [comment]
@wanght3w does @wshengqi response solve your trouble？

**Comment by wanght3w** [comment]
> @wanght3w does @wshengqi response solve your trouble？

嗯，但是我还有个可能不太相干的问题，就是现在没有云端，如何自己建立一个简单的云端（或者说服务器）来建立HttpPost请求的接口，接受通过HttpExport导出的数据。

**Comment by badboy-huaqiao** [comment]
@wshengqi

**Comment by wshengqi** [comment]
@wanght3w 你可以自己写一个简单的http接口服务，比如go，Python，java都可以，然后在UI的AppService界面，HttpExport的参数的url中，写上你的接口服务的数据接收地址，并且部署到edgex Consul，就可以了，like this：
func ReceiveDataPostJSON(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	err := r.ParseForm()
	if err != nil {
		log.Fatal("parse form error ",err)
	}
	formData := make(map[string]interface{})
	json.NewDecoder(r.Body).Decode(&formData)
	jsonData, err := json.Marshal(formData)
	if err != nil {
		log.Printf(err.Error())
		http.Error(w, "InternalServerError", http.StatusInternalServerError)
		return
	}
	formatTimeStr:=time.Unix(time.Now().Unix(),0).Format("03:04:05")
	data["time"] = formatTimeStr
	data["currentData"] = string(jsonData)
}

**Comment by badboy-huaqiao** [comment]
@wanght3w 你的问题是否得到了解决？

**Comment by wanght3w** [comment]
> @wanght3w 你的问题是否得到了解决？

解决了
