### ISSUE TITLE
Can not create rule via  edgex console  (1.2.1 version)

### ISSUE THREAD

**Issue by tianxingguo** [edgexfoundry/edgex-ui-go#252]
![error](https://user-images.githubusercontent.com/12626589/85959504-63aef280-b9cf-11ea-8cf5-16f401297fa2.png)

So can not submit when press submit button

**Comment by badboy-huaqiao** [comment]
@wshengqi

**Comment by DaveZLB** [comment]
@tianxingguo 
EdgeX Geneva uses a new rule engine kuiper, which works differently than the previous Java version. In UI v1.2.1, the new version rule engine has not been adapted. If you need to use the old rule engine, You need to modify the docker compose file to use the old version rules engine. If you want to use rule engine in UI,  you should modify [docker-compose-geneva-mongo-no-secty.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/geneva/compose-files/docker-compose-geneva-mongo-no-secty.yml), Uncomment  the old java rule engine part to replace kuiper rule engine.
![image](https://user-images.githubusercontent.com/29951254/85980768-97147000-ba15-11ea-9f8f-26e373cfde03.png)

if you want to know kuiper, please refer to kuiper doc https://github.com/emqx/kuiper.

**Comment by tianxingguo** [comment]
@DaveZLB  Thanks a lot , I checked the version, is Geneva  version, docker images' version is 1.2.1.

**Comment by tianxingguo** [comment]
@DaveZLB 
just go through littel code of ui, found the code of ruleengine.js is different with device profile definition:

Profile definition:
![profile](https://user-images.githubusercontent.com/12626589/86004843-731d5280-ba46-11ea-9908-371ee4620ed9.png)

rueengine.js code:
![ruleengine](https://user-images.githubusercontent.com/12626589/86004966-9a741f80-ba46-11ea-8183-b4d1c5a0d08d.png)

**Comment by wangmingjunabc** [comment]
在添加规则引擎，Action栏目，选择好了设备后，对应的command下拉按钮不能正常显示

**Comment by wangmingjunabc** [comment]
> ![error](https://user-images.githubusercontent.com/12626589/85959504-63aef280-b9cf-11ea-8cf5-16f401297fa2.png)
> 
> So can not submit when press submit button

你这个问题解决了吗？

**Comment by DaveZLB** [comment]
您好，目前最新Geneva版本里面使用的规则引擎是kuiper，页面还有没做适配，红点表示这个功能不可用

**Comment by tianxingguo** [comment]
Just modified the UI code, change d.profile.commands to d.profile.deviceCommands , 

![fixed](https://user-images.githubusercontent.com/12626589/86710957-0e698580-c04e-11ea-810e-99b9ea2387e2.png)

**Comment by badboy-huaqiao** [comment]
@tianxingguo 👍，nice catch，thanks for your feedback，please push your code freely, and @wangmingjunabc if you are using the existing Rule service, ollow @tianxingguo  's instructions to make changes, I think it's been resolved, so I close it now
