### ISSUE TITLE
DeviceAddressable protocol can not be customized

### ISSUE THREAD

**Issue by wangmingjunabc** [edgexfoundry/edgex-ui-go#255]
![image](https://user-images.githubusercontent.com/4217301/89988301-eb1ba100-dcb1-11ea-9d9b-789120d7a75f.png)
when adding new device,only three iot protocol can be selected。The choice should be based on the iot device I add, such as HTTP etc.

**Comment by badboy-huaqiao** [comment]
@wangmingjunabc select others, which you can create by your custom device service implementation.

**Comment by wangmingjunabc** [comment]
> @wangmingjunabc select others, which you can create by your custom device service implementation.
select others can not take effect，when I use the device-camera-go device service from community。HTTP is explicitly used。
![image](https://user-images.githubusercontent.com/4217301/90098738-7dcc4680-dd6b-11ea-93c1-ff89a1fb4ffe.png)。
Manually filling out can be more flexible。

**Comment by wshengqi** [comment]
@wangmingjunabc This issue is a bug, we should add a new key in this DeviceAddressable Select names HTTP, and if you want to use HTTP , you can custom parameters. like this configuration.toml  
https://github.com/edgexfoundry/device-camera-go/blob/master/cmd/res/configuration.toml
 [DeviceList.Protocols.HTTP]
      Address = '192.168.2.105'
![image](https://user-images.githubusercontent.com/51698380/90108562-17502400-dd7d-11ea-8e6a-395043e59e2c.png)

and we will fix this son. this issue was look good to me, thank you

**Comment by wangmingjunabc** [comment]
> @wangmingjunabc This issue is a bug, we should add a new key in this DeviceAddressable Select names HTTP, and if you want to use HTTP , you can custom parameters. like this configuration.toml
> https://github.com/edgexfoundry/device-camera-go/blob/master/cmd/res/configuration.toml
> [DeviceList.Protocols.HTTP]
> Address = '192.168.2.105'
> ![image](https://user-images.githubusercontent.com/51698380/90108562-17502400-dd7d-11ea-8e6a-395043e59e2c.png)
> 
> and we will fix this son. this issue was look good to me, thank you
I think it would be more accurate to read it from addressable field of device Service。when add a device, firstly we should select its device service。And the device service has  the IoT protocol info。
![image](https://user-images.githubusercontent.com/4217301/90115129-415a1400-dd86-11ea-8dd1-344be7fec461.png)

**Comment by badboy-huaqiao** [comment]
@wangmingjunabc thanks for your feedback, it's absolutely better if you can submit bug fix code. 
so  does @wshengqi 's reply resolving your trouble ? if done, I will close it now.

and we are plan to create a product-level user interface in the future. 
thanks for your feedback again.

**Comment by wangmingjunabc** [comment]
done
