### ISSUE TITLE
EdgeX Foundry Console->export :can not add 

### ISSUE THREAD

**Issue by jackding20191205** [edgexfoundry/edgex-ui-go#264]
can not add new client when I want to export 

![image](https://user-images.githubusercontent.com/58494938/94412619-932af200-01ac-11eb-834d-452a5af27a07.png)
![add fail](https://user-images.githubusercontent.com/58494938/94412821-dab17e00-01ac-11eb-912e-d6078fe720d9.png)

**Comment by jackding20191205** [comment]
![image](https://user-images.githubusercontent.com/58494938/94413181-4eec2180-01ad-11eb-84c8-eed8360ea43d.png)

**Comment by jackding20191205** [comment]
I wan to export mqtt service data ,but I failed  when I  do "add "

**Comment by badboy-huaqiao** [comment]
@wshengqi

**Comment by jackding20191205** [comment]
any suggestion?

**Comment by jackding20191205** [comment]
addtion:
![image](https://user-images.githubusercontent.com/58494938/94415700-7abcd680-01b0-11eb-9a0e-efe5770fdd7b.png)

I tried version docker-edgex-ui-go-arm641.2.1,1.2.0,1.1.0,1.0.0,they have the same problem above

**Comment by wshengqi** [comment]
@jackding20191205 
Hi , sorry im late for your question,  The functionality of this Export  module has been abandoned, and you can use the new functioins AppServices or Rule Engine to export your device data. like this :
![image](https://user-images.githubusercontent.com/51698380/94637743-e5822500-030a-11eb-82bc-0c818715fc85.png)

Step 1: Click the AppServices, and choose the App service in selete input.
Step 2: Drag the Transforms - Filtering - FilterByDeviceName to the left box.
Step 3: Drag the Transforms - Export - HTTPPostJSON to the left box. (For example , you can drag MQTTsend also)
Step 4: Click this two button names [Set Params] to select your device and to input the address of data receiving end.
Step 5: Click [Refresh Consul] , and you will see the device data in your end point.

Thank you for your question, if you have any problem, you can ask me at any time.

**Comment by jackding20191205** [comment]
thanks, it works  follow your advice  above

**Comment by jackding20191205** [comment]
another problem：in order to test the export function,when I get value,I can subscrib correct result; but when I set new value, I can subscrib nothering ；
![Uploading image.png…]()

**Comment by jackding20191205** [comment]
@wshengqi 
any  adevice ?

**Comment by wshengqi** [comment]
@jackding20191205 This problem may be the Set value Request is not save in the Edgex Database, The export function is an Application Service in EdgexFoundry, this App service will do Query follow configuration form Edgex Database. you can see the set data is already saved or not.

**Comment by jackding20191205** [comment]
@wshengqi   how to see whether  the set data is already saved ? I am a new studutent in edgexfoundry.

**Comment by wshengqi** [comment]
@jackding20191205 I saw this problem again, may be you can see the data like this:
![image](https://user-images.githubusercontent.com/51698380/95826243-97d2d700-0d64-11eb-9fc1-fc2d37750cae.png)

those data means the Device send data to Edgex, if you want to see your custom data, you should use send data from Device to Edgex.  In this my picture demo , the Random-Integer-Device will send data to Edgex automatically.

another way if you wangt to see the Edgex Data, you can call Edgex OpenAPI , different api match different data. this is OpenAPI address:    https://github.com/edgexfoundry/edgex-go/tree/master/openapi/v1

And last, we will write a new page to display many of Edgex data in the future.

**Comment by jackding20191205** [comment]
thanks

**Comment by wshengqi** [comment]
@jackding20191205 Please close this issue, thank you.
