### ISSUE TITLE
how to  use scheduler

### ISSUE THREAD

**Issue by jackding20191205** [edgexfoundry/edgex-ui-go#267]
I wan to use scheduler to get mqtt parameter every minite, but failed when I add interval.
![image](https://user-images.githubusercontent.com/58494938/96396937-f2ec4a00-11fa-11eb-8e45-3b4d2315bec9.png)

**Comment by jackding20191205** [comment]
@wshengqi

**Comment by wshengqi** [comment]
@jackding20191205 Hi, i think you faild to connecting with Edgex , because UI Health check is red , please check the UI connection.
 If you use docker file , check the [network] in the Yml file. If you use source code , you can check [Hose] in the configuration.toml file.

**Comment by jackding20191205** [comment]
![image](https://user-images.githubusercontent.com/58494938/96680018-4bf8e100-13a7-11eb-9de7-27184bc5d46b.png)
@wshengqi  I do not why this micro service fail to start

**Comment by jackding20191205** [comment]
@wshengqi   any advice ?

**Comment by wshengqi** [comment]
@jackding20191205 sorry I'm late, Has this problem been solved ?
