### ISSUE TITLE
Add Makefile targets to build docker image

### ISSUE THREAD

**Issue by JPWKU** [edgexfoundry/edgex-ui-go#28]
Both master and delhi branches need modifications to the Makefile; add targets to build the docker image.  Please have a look at how this is handled here https://github.com/edgexfoundry/edgex-go/blob/master/Makefile.
Specifically we need a target called `docker` that builds all relevant images.

**Comment by badboy-huaqiao** [comment]
@JPWKU ok, i will do that , but the Dockerfile i written has some problem, because of the structure of the project,the execute file by command ` make build` also need to been treated as a static web server ,so the Dockerfile is more difficulty to be written, , i will test it after i finished it.

**Comment by JPWKU** [comment]
@badboy-huaqiao Hmm, ok.  Does it make sense for this to be dockerized?

**Comment by JPWKU** [comment]
Well I think since you already have it going, we can publish it.  If we discover issues we can always have a patch release of it.

**Comment by badboy-huaqiao** [comment]
> @badboy-huaqiao Hmm, ok. Does it make sense for this to be dockerized?
@JPWKU hi, maybe i misunderstood what you say, or you misunderstood mine, sorry about my poor english, but i saw your msg `Both master and delhi branches need modifications to the Makefile; add targets to build the docker image.`, so i think if add `make docker` command to Makefile, when user see that, they might try to use it , but if the problems i mentioned before not to be fixed, the `make docker` will not work.

**Comment by badboy-huaqiao** [comment]
it's done ! i close it now
