### ISSUE TITLE
How to upload data collected during disconnection?

### ISSUE THREAD

**Issue by themeyic** [edgexfoundry/edgex-ui-go#283]
Excuse me, for example, when I disconnect the network and the data is temporarily stored locally at the edge, how to upload the data collected during the disconnection to the cloud after connecting to the network?

**Comment by badboy-huaqiao** [comment]
@themeyic Sorry for the late reply, the feature above you mentioned is not belonged to UI, it should be the part of edgex self, you can create an associated issue to edgex-go project.

**Comment by badboy-huaqiao** [comment]
closed for timeout
