### ISSUE TITLE
Prepare to build project and PRs with Jenkins

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-ui-go#3]
some procedure list below: 

for go:
- [go test]() (must)
- [go fmt](https://golang.org/pkg/fmt/) (must)
- [go vet](https://golang.org/cmd/vet/) (must)
- [gosimple](https://github.com/dominikh/go-tools/blob/master/cmd/gosimple) (optional)
- [keyify](https://github.com/dominikh/go-tools/blob/master/cmd/keyify)
- [staticcheck](https://github.com/dominikh/go-tools/blob/master/cmd/staticcheck)
- [unused](https://github.com/dominikh/go-tools/blob/master/cmd/unused)
- [golint](https://github.com/golang/lint)
- [misspell](https://github.com/client9/misspell)
- [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports)
- [errcheck](https://github.com/kisielk/errcheck)
- [aligncheck](https://github.com/opennota/check)
- [structcheck](https://github.com/opennota/check)
- [varcheck](https://github.com/opennota/check)
- ...

(We can also refer to edgex-go)

for javascript:
- [jslint](https://www.jslint.com/)
- ...

for css:
- [csslint](https://github.com/CSSLint/csslint)
- ...

**Comment by yanghua** [comment]
@jpwhitemn and @JPWKU The discussion about jenkins build here, my personal suggestion is to follow the most basic check of edgex-go, I suggest to merge the [PR about the migration](https://github.com/edgexfoundry/edgex-ui-go/pull/2) as soon as possible, and ensure that the CI service is available before we receive other PRs. Then we refine it and add more tools to ensure code quality and more test coverage.

**Comment by badboy-huaqiao** [comment]
@yanghua it's good , if you are familiar with jenkins, you can share your demo, we have a zoom chat channel  
https://VMware.zoom.us/j/3697467292

**Comment by anonymouse64** [comment]
There are still some problems with the jenkins jobs here. For example, the merge master job has been consistently failing:
See https://jenkins.edgexfoundry.org/view/Merge-Jobs/job/edgex-ui-go-master-merge-go/37/console:
```
02:46:47 The push refers to repository [nexus3.edgexfoundry.org:10003/docker-edgex-ui-go]
02:46:47 8e391bfed792: Preparing
02:46:47 721384ec99e5: Preparing
02:46:47 721384ec99e5: Layer already exists
02:46:49 8e391bfed792: Pushed
02:46:49 5942a5919b84b6304aa157f8c0f3231a436edf31-0.2.0: digest: sha256:a6de472697c961657e3bf53ba72d29c97419525481afa6f96806d92758e5637c size: 739
02:46:49 cp: cannot stat ‘cmd/edgex-ui-go/edgex-ui-go’: No such file or directory
02:46:49 Build step 'Execute shell' marked build as failure
```

The stage jobs seem to fail from the same thing. See https://jenkins.edgexfoundry.org/job/edgex-ui-go-master-stage-go/221/console:
```
12:49:01 The push refers to repository [nexus3.edgexfoundry.org:10004/docker-edgex-ui-go]
12:49:01 d53e82380b67: Preparing
12:49:01 721384ec99e5: Preparing
12:49:01 721384ec99e5: Layer already exists
12:49:03 d53e82380b67: Pushed
12:49:04 5942a5919b84b6304aa157f8c0f3231a436edf31-0.2.0: digest: sha256:f0058c9538f93d25720c35db32b72ce35fcb58ea04e0e3c699427769f9618ec6 size: 739
12:49:04 The push refers to repository [nexus3.edgexfoundry.org:10004/docker-edgex-ui-go]
12:49:04 d53e82380b67: Preparing
12:49:04 721384ec99e5: Preparing
12:49:04 721384ec99e5: Layer already exists
12:49:04 d53e82380b67: Layer already exists
12:49:04 0.2.0: digest: sha256:f0058c9538f93d25720c35db32b72ce35fcb58ea04e0e3c699427769f9618ec6 size: 739
12:49:04 cp: cannot stat ‘cmd/edgex-ui-go/edgex-ui-go’: No such file or directory
12:49:04 Build step 'Execute shell' marked build as failure
```

The verify jobs however seem to be working fine.

If the stage and merge jobs can be fixed then I think this issue could be closed

**Comment by lranjbar** [comment]
Issue seems stale
