### ISSUE TITLE
Can not edit device in new UI

### ISSUE THREAD

**Issue by gao270615179** [edgexfoundry/edgex-ui-go#365]
Can not edit device in new UI. click edit button, the request url is `http://127.0.0.1:4000/api/v2/device/name/deviceName`, not contain `metadata`.
The correct request url should be `http://127.0.0.1:4000/metadata/api/v2/device/name/deviceName`

**Comment by badboy-huaqiao** [comment]
@gao270615179 I didn't meet the situation you mentioned above, could you provision some more details about what you encounter? such as the version of UI, error logs, or sreenshots , etc.

**Comment by gao270615179** [comment]
@badboy-huaqiao 
UI master branch:
```
    findDeviceByName(name) {
        let url = `${this.findDeviceByNameUrl}/${name}`;
        return this.http.get(url).pipe(Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_2__["catchError"])(error => this.errorSvc.handleError(error)));
    }
```
There has extra `/` in url. Then I remove the `/`, it is normal.

`findProfileByName` has also this problem.

**Comment by badboy-huaqiao** [comment]
@gao270615179 Good Catch!  I figured it out that when I use the built UI,  it seems like that there are some different stuffs between the built product environment and my develop env,  which is the reason why I didn't encounter that before. 

great thanks for your feedback, we will fix that and enhance the built UI test works !

**Comment by badboy-huaqiao** [comment]
done!
