### ISSUE TITLE
Use default value in Set command

### ISSUE THREAD

**Issue by gao270615179** [edgexfoundry/edgex-ui-go#384]
In `Set` device command, when some parameter is empty(not fill any value), don't put it in request body. Then, Device SDK can use command default value or resource default value as the value of that parameter.

In `web/src/app/metadata/device/device-list/device-list.component.ts` line 324, add  
```
if($(`#${p.resourceName}`).val().trim() != "")
```
then:
```
    this.selectedCmdSetParams?.forEach(function (p) {
      if($(`#${p.resourceName}`).val().trim() != "") {
        params[p.resourceName] = $(`#${p.resourceName}`).val().trim();
      }
    });
```

Maybe, this is not appropriate for String value type.

**Comment by gao270615179** [comment]
Sorry, maybe should use other method until now. Device SDK will parse count of parameters, if the count is 0, it will return error(no parameters specified).

**Comment by badboy-huaqiao** [comment]
@gao270615179 hi gao, that's really a good catch! 👍  I‘m really glad to see your feedback again, now, we indeed need more manpower,  so would you like to submit your code here?

**Comment by gao270615179** [comment]
@badboy-huaqiao Sorry, I don't know angular and TypeScript😂. And I tried to setup a development environment to build web src, but it failed.

**Comment by badboy-huaqiao** [comment]
@gao270615179 that's okay, I'll fix it,  looking forward more feedbacks from your efforts.

**Comment by gao270615179** [comment]
Device SDK has issued problem that using default value of parameter when the count of parameters is 0.

https://github.com/edgexfoundry/device-sdk-go/pull/978
```
remove empty request body check to allow default value usage
```
