### ISSUE TITLE
edit stream occurs error

### ISSUE THREAD

**Issue by ccb1900** [edgexfoundry/edgex-ui-go#408]
![image](https://user-images.githubusercontent.com/3932305/123721341-ab08e100-d8b8-11eb-9832-c02d3bf636cb.png)

when i change my layout stream in rule engine ,i got it

405 is http method error.

can i only create one stream?

i think notification should  disappear in some time like 5 second

![image](https://user-images.githubusercontent.com/3932305/123726406-7c900380-d8c2-11eb-9eb6-82aceaf7a276.png)

sendSingle should be boolean type

**Comment by badboy-huaqiao** [comment]
see PR-#502, it's done!
