### ISSUE TITLE
Getting an Http failure response for http://localhost:4000

### ISSUE THREAD

**Issue by ansel2000** [edgexfoundry/edgex-ui-go#422]
Hey I'm new to EdgeX and was following the **EdgeX Foundry: A hands-on tutorial** PDF for the Geneva Version.
I am able to add devices and update them using requests through postman. I am however unable to do the same through the gui as
I get the error "code: 404 , message: Http failure response for http://localhost:4000/metadata/api/v2/deviceprofile/all?offset=0&limit=5: 404 Not Found "

**Comment by ansel2000** [comment]
Link to the PDF [https://docs.edgexfoundry.org/1.2/examples/LinuxTutorial/EdgeX-Foundry-tutorial-ver1.0.pdf](url)

**Comment by badboy-huaqiao** [comment]
@ansel2000 Hi, it looks like the GUI you are using is Ireland version, but EdgeX is Geneva version, you should use the same version of them.

**Comment by ansel2000** [comment]
@badboy-huaqiao Yes. Thanks for pointing that out. Just fixed it. Cheers.
