### ISSUE TITLE
edgex console web show 502 Bad Gateway

### ISSUE THREAD

**Issue by jackeyycl** [edgexfoundry/edgex-ui-go#435]
![1631867058(1)](https://user-images.githubusercontent.com/21978361/133750281-c4e7776b-742e-4fe6-a7ac-fe1aa70f93a9.png)
I  run the edgex core services by docker-compose , then get and run the edgex-ui-go from https://github.com/edgexfoundry/edgex-ui-go. 
when i open the http://localhost:4000, find 502 errors ,and does not have any correct data.

here is my dockers.
$ sudo docker ps -a 
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS                   PORTS                                                                                                  NAMES
41c57db28058        edgexfoundry/docker-device-modbus-go:1.2.1           "/device-modbus --cp…"   5 hours ago         Up 5 hours               127.0.0.1:49991->49991/tcp                                                                             edgex-device-modbus
bcd7efee5233        emqx/kuiper:0.4.2-alpine                             "/usr/bin/docker-ent…"   24 hours ago        Up 5 hours               127.0.0.1:20498->20498/tcp, 9081/tcp, 127.0.0.1:48075->48075/tcp                                       edgex-kuiper
8cee7edb97cf        edgexfoundry/docker-sys-mgmt-agent-go:1.2.1          "/sys-mgmt-agent -cp…"   24 hours ago        Up 5 hours               127.0.0.1:48090->48090/tcp                                                                             edgex-sys-mgmt-agent
6c7fb684d250        edgexfoundry/docker-device-rest-go:1.1.1             "/device-rest-go --c…"   24 hours ago        Up 5 hours               127.0.0.1:49986->49986/tcp                                                                             edgex-device-rest
45d43c21b0ee        edgexfoundry/docker-app-service-configurable:1.2.0   "/app-service-config…"   24 hours ago        Up 5 hours               48095/tcp, 127.0.0.1:48100->48100/tcp                                                                  edgex-app-service-configurable-rules
b53efb1f3b2c        edgexfoundry/docker-device-virtual-go:1.2.2          "/device-virtual --c…"   24 hours ago        Exited (0) 5 hours ago                                                                                                          edgex-device-virtual
176fe95917da        edgexfoundry/docker-core-data-go:1.2.1               "/core-data -cp=cons…"   24 hours ago        Up 5 hours               127.0.0.1:5563->5563/tcp, 127.0.0.1:48080->48080/tcp                                                   edgex-core-data
2ec1b8d1a486        edgexfoundry/docker-core-command-go:1.2.1            "/core-command -cp=c…"   24 hours ago        Up 5 hours               127.0.0.1:48082->48082/tcp                                                                             edgex-core-command
24e6d45b0ea3        edgexfoundry/docker-core-metadata-go:1.2.1           "/core-metadata -cp=…"   24 hours ago        Up 5 hours               127.0.0.1:48081->48081/tcp                                                                             edgex-core-metadata
d842c004c0c9        edgexfoundry/docker-support-scheduler-go:1.2.1       "/support-scheduler …"   24 hours ago        Up 5 hours               127.0.0.1:48085->48085/tcp                                                                             edgex-support-scheduler
5b4f9f010efa        edgexfoundry/docker-support-notifications-go:1.2.1   "/support-notificati…"   24 hours ago        Up 5 hours               127.0.0.1:48060->48060/tcp                                                                             edgex-support-notifications
b55ebee7b368        redis:5.0.8-alpine                                   "docker-entrypoint.s…"   24 hours ago        Up 5 hours               127.0.0.1:6379->6379/tcp                                                                               edgex-redis
96f82dd7749c        edgexfoundry/docker-edgex-consul:1.2.0               "edgex-consul-entryp…"   24 hours ago        Up 5 hours               127.0.0.1:8400->8400/tcp, 8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 127.0.0.1:8500->8500/tcp   edgex-core-consul

**Comment by badboy-huaqiao** [comment]
@jackeyycl it seem like you are using EdgeXFoundry version1.2.1 and the GUI version2.0, incompatible between different versions, please use the same version of them, here is the docker compose file for released v2.0 [https://github.com/edgexfoundry/edgex-compose/blob/v2.0.0/docker-compose-no-secty-with-ui.yml](https://github.com/edgexfoundry/edgex-compose/blob/v2.0.0/docker-compose-no-secty-with-ui.yml).

and if you want to run GUI in source code, don't forget to change the host ip in `cmd/edgex-ui-server/res/configuration.toml` of where EdgeX instance running.

**Comment by jackeyycl** [comment]
> @jackeyycl it looks like you are using EdgeXFoundry version1.2.1 and the GUI version2.0, incompatible between different versions, please use the same version of them, here is the docker compose file for released v2.0 https://github.com/edgexfoundry/edgex-compose/blob/v2.0.0/docker-compose-no-secty-with-ui.yml.
> 
> and if you want to run GUI in source code, don't forget to change the host ip in `cmd/edgex-ui-server/res/configuration.toml` of where EdgeX instance running.



> @jackeyycl it looks like you are using EdgeXFoundry version1.2.1 and the GUI version2.0, incompatible between different versions, please use the same version of them, here is the docker compose file for released v2.0 https://github.com/edgexfoundry/edgex-compose/blob/v2.0.0/docker-compose-no-secty-with-ui.yml.
> 
> and if you want to run GUI in source code, don't forget to change the host ip in `cmd/edgex-ui-server/res/configuration.toml` of where EdgeX instance running.

does work! Thanks lot!~~
