### ISSUE TITLE
Edgex ui return 500 registry is required

### ISSUE THREAD

**Issue by SpAndrea117** [edgexfoundry/edgex-ui-go#439]
Hi everybody, 
I'm trying to start EdgeX ui on my machine, using k3s. Using the docker.yml everything works correctly, meanwhile using k3s, the UI brakes with the following error:

```
error:
apiVersion: "v2"
message: "registry is required"
statusCode: 500
__proto__: Object
headers: d {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure response for http://localhost:4000/system/api/v2/system/health?services=core-metadata,core-data,core-command,support-notifications,support-scheduler,app-rules-engine: 500 Internal Server Error"
name: "HttpErrorResponse"
ok: false
status: 500
statusText: "Internal Server Error"
url: "http://localhost:4000/system/api/v2/system/health?services=core-metadata,core-data,core-command,support-notifications,support-scheduler,app-rules-engine"
```

The EdgeX core miscroservices are up and works correctly and the API are accessible from the localhost through a remapping.

Thanks for the support

**Comment by badboy-huaqiao** [comment]
Hi @SpAndrea117 I‘m not familiar with k3s, but there is a work deployment file with k8s I did not long ago, [click here](https://github.com/edgexfoundry/edgex-examples/blob/main/deployment/kubernetes/k8s-hanoi-redis-no-secty.yml),  which used old edgex released version.
I don't know what ways you started the EdgeX with GUI, if you used docker image it should work, but if you start it with code source, you should address host IP of each microservice in the res/configuration.toml of GUI.
hope that help you.

**Comment by SpAndrea117** [comment]
Thanks @badboy-huaqiao, i've exposed the nodeports within the range 30000 32767 for each mircroservice, so that I can access each service from localhost, changing these informations Aldo within the configuration.toml file of the edgex UI.
I Will check your work as soon as possibile.
Thanks for the support.

Scarica Outlook per Android<https://aka.ms/AAb9ysg>


Andrea Spampinato

Concept Reply
Via Cardinal Massaia, 83
10147 - Torino - ITALY
phone: +39 011 29100
***@***.******@***.***>
www.reply.it

[Concept Reply]
________________________________
