### ISSUE TITLE
[Metadata] Review allowable edit operations for devices

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-ui-go#452]
@iain-anderson @lenny-intel 

The latest version (see details below) of the UI allows a user to edit some fields of a device which shouldn't be permitted.

For instance the UI currently allows someone to change the `operatingState` of a device. This is an attribute managed by a device service, and shouldn't be settable externally.

Likewise, there are Device Service and Device Profile lists with checkboxes for each item listed. Is the intent to allow someone to change the Device Service or Profile of a device using these lists?

I do think that allowed AutoEvents to be added or edited should be allowed, but not so sure about ProtocolProperties, as in general these should be set by device services, not external clients.

I would expect that Core Metadata would already prevent some of these operations, if not, maybe this is something we need to review asap (i.e. before code freeze for Jakarta).

Version:
I ran the UI using the edgex-ui snap from edge channel. Please note that the version of this snap incorrectly shows 1.0 vs. 2.0.1-dev.18). I also testing using the ireland version of the edgexfoundry snap:

```
$ snap list | grep edgex
edgex-ui           1.0                 23     latest/edge      canonical*  -
edgexfoundry       2.0.0-2             3196   2.0/stable       canonical*  -
```

**Comment by badboy-huaqiao** [comment]
> For instance the UI currently allows someone to change the `operatingState` of a device. This is an attribute managed by a device service, and shouldn't be settable externally.

where can I find corresponding documents indicates this feature? I remember I had done the tesing work not so long ago and it works good, is this a new feature of Jakarta?

**Comment by tonyespy** [comment]
@badboy-huaqiao this was discussed at this week's device service's WG meeting, and the general consensus was that modifications to ProtocolProperties were OK.

That said, the opinion offered was also that modifying `operatingState` was OK too, as it could be used to reset via operator intervention, although I disagree with that opinion.  A similar statement was made about `deviceService` (i.e. that it is modifiable), however I disagree with that as well.

@iain-anderson can please offer your opinion why someone should be able to modify these two fields? 

@cloudxxx8 do we allow a device's`deviceService` and `operatingState` to be modified, and if so, why?

**Comment by cloudxxx8** [comment]
@tonyespy we allow `operatingState` to be modified from API, but this is for the Device Service to call, not user.
we allow `deviceService` to be modified because if the user wants to deploy multiple Device Service instances.
we made proper callback to handle this `deviceService` modification in the SDK

**Comment by badboy-huaqiao** [comment]
@iain-anderson @tonyespy that's mean both `AdminState` and `OperatingState` could be changed on the GUI by users,  do I make sense?

**Comment by jpwhitemn** [comment]
@badboy-huaqiao - your above statements are correct.  The GUI should be allowed to change the AdminState but not the Operating State.  The GUI can (and should) display the operating state so that the user sees that their may be an issue, but the operating state change is reserved for device services (internally) only and not modified by the GUI.
