### ISSUE TITLE
Rule engine UI issues wrong data type for sendSingle property

### ISSUE THREAD

**Issue by ngjaying** [edgexfoundry/edgex-ui-go#471]
This is a problem opened in eKuiper issus: [Rule stopped: canceled manually or by error](https://github.com/lf-edge/ekuiper/issues/1055). The sendSingle must be a bool instead of a string type. It is likely that the UI post a wrong data type for sendSingle property.

**Comment by badboy-huaqiao** [comment]
rule module on GUI needs to be redesigned

**Comment by jdevoo** [comment]
Thank you both!

**Comment by badboy-huaqiao** [comment]
see PR-#502, it's done!
