### ISSUE TITLE
Errors in UI when support-notifications, support-scheduler, rule engine and sys-mgmt-agent are not running

### ISSUE THREAD

**Issue by MonicaisHer** [edgexfoundry/edgex-ui-go#472]
### Affected Services
scheduler 
notifications
kuiper/rule-engine  
sys-mgmt-agent

#### Install: 
```
$ snap install edgex-ui --edge
$ snap install edgexfoundry --edge
```
#### Generate a token:

1. Generate a public/private keypair
```
$ openssl ecparam -genkey -name prime256v1 -noout -out private.pem
$ openssl ec -in private.pem -pubout -out public.pem
```
2.  Configure user and public-key
```
$ sudo snap set edgexfoundry env.security-proxy.user=user01,USER_ID,ES256
$ sudo snap set edgexfoundry env.security-proxy.public-key="$(cat public.pem)"
```
3. Generate a token
```
$ edgexfoundry.secrets-config proxy jwt --algorithm ES256 \
 --private_key private.pem --id USER_ID --expiration=1h
```

Notice that [localhost:4000](http://localhost:4000/en-US/#/dashboard) shows errors:
![image](https://user-images.githubusercontent.com/57879268/140491686-1a56b769-7fb6-4ca3-9142-1c9f270976d5.png)
```
code: undefined , message: An invalid response was received from the upstream server
```
These logs will be removed seperately after enabling each four services to avoid runtime errors:
```
$ sudo snap set edgexfoundry support-scheduler=on 
$ sudo snap set edgexfoundry support-notifications=on 
$ sudo snap set edgexfoundry sys-mgmt-agent=on
$ sudo snap set edgexfoundry kuiper=on
```
### Deployment Environment:
Ubuntu 20.04 LTS

EdgeX Version:
EdgeX built from latest master branch (i.e. nightly build as of Nov 4 '21)

Anything else relevant?
Please see the related PR #470

support-notifications, support-scheduler, rule engine and sys-mgmt-agent services shouldn't output error logs, since they are disabled by default, and users can decide if they wish to use these services in the UI or not. Instead, I suggest there could be hints in the UI suggest that if users wish to use these services then users need to turn on according services first.

**Comment by badboy-huaqiao** [comment]
In general,edgex is a microservices architecture, the GUI does not have the ability to know which services the user has started in time except edgex providing a out api allowing GUI or other third party application do that, but your advice is a good idea imporving user exceperience, we need a disscuss to find out a way to fix this issue, keep this issue open until it's done

**Comment by MonicaisHer** [comment]
@badboy-huaqiao  Thanks, it should be treat as an enhancement.

**Comment by badboy-huaqiao** [comment]
move to issue #474 , PR #491, it's done

**Comment by MonicaisHer** [comment]
Thanks for the PR@badboy-huaqiao. The UI provides instructions of the service is unavailable now, but the popup messages are still here.

![image](https://user-images.githubusercontent.com/57879268/158589693-8abd85bc-f067-47f6-9a59-baaa8f92acf1.png)

**Comment by badboy-huaqiao** [comment]
@MonicaisHer Hi, I'm now working on this issue, but I didn't encounter the problem when navigating to ruleengine menu item. can you give me your operation steps how you encountered the popup message?

**Comment by MonicaisHer** [comment]
@badboy-huaqiao  
1. Install latest versions:
```
snap install edgexfoundry --edge
snap install edgex-ui --edge
```
2. [Generate access token](https://github.com/edgexfoundry/edgex-ui-go/tree/main/snap#jwt-token):
```
# Create private key:
openssl ecparam -genkey -name prime256v1 -noout -out private.pem

# Create public key:
openssl ec -in private.# set user=username,user id,algorithm (ES256 or RS256)
sudo snap set edgexfoundry env.security-proxy.user=user01,USER_ID,ES256

# set public-key to the contents of a PEM-encoded public key file
sudo snap set edgexfoundry env.security-proxy.public-key="$(cat public.pem)"pem -pubout -out public.pem
# get token
TOKEN=`edgexfoundry.secrets-config proxy jwt --algorithm ES256 --private_key private.pem --id USER_ID --expiration=1h`

# Keep this token in a safe place for future reuse as the same token cannot be regenerated or recovered using the secret-config CLI
echo $TOKEN
```

**Comment by badboy-huaqiao** [comment]
@MonicaisHer sorry, when exec `snap set edgexfoundry env.security-proxy.user=user01,USER_ID,ES256`, I got error: error: snap "edgexfoundry" not found, my environment is CentOS7

**Comment by MonicaisHer** [comment]
@badboy-huaqiao Thanks.
Here are the [install steps](https://snapcraft.io/install/edgexfoundry/centos#install) for centOS:
```
sudo yum install epel-release
sudo yum install snapd
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap
sudo snap install edgexfoundry
```

**Comment by badboy-huaqiao** [comment]
@MonicaisHer thanks, when exec `snap install edgexfoundry` I got
```
error: cannot perform the following tasks:
- Mount snap "edgexfoundry" (3375) (snap "edgexfoundry" system usernames require a snapd built against libseccomp >= 2.4)
```

**Comment by badboy-huaqiao** [comment]
@MonicaisHer I got the reason by google, maybe I should upgrade to CentOS8.

> There is no different version of snapd for RHEL7/CentOS7 than one available from EPEL7 repo.
> 
> From what I can tell, RHEL7 has libseccomp 2.3.1. You could build libseccomp and snapd yourself, the src.rpms are available. I’m not sure it’s worth the hassle though. Libseccomp is used by a number of packages which you’d likely need to rebuild too. Parallel installing or bundling a newer libseccomp in snapd is probably less work, yet still non trivial
> 
> You may consider using RHEL8/Centos8 which has libseccomp 2.4.1.

**Comment by badboy-huaqiao** [comment]
@MonicaisHer but it's strange that not encountering to popup message under docker container mode.

**Comment by MonicaisHer** [comment]
> @MonicaisHer but it's strange that not encountering to popup message under docker container mode.

edgexfoundry snap and edgex-ui snap are all built from the latest source code. Which version of edgex in your docker container was used?

**Comment by badboy-huaqiao** [comment]
@MonicaisHer I used `nexus3.edgexfoundry.org:10004/edgex-ui:latest` which will be built and updated everytime when one PR is merged. Also I just test it with source code, I'm still not  encounter the message popup when ruleengine service is down.  

are you sure you saw the popup message when navigating to ruleengine not another module page? the dashboard and app service module page will still popup error message if all the services of edgex is down, because dashboard and app service  is not a real service  of edgex.

**Comment by badboy-huaqiao** [comment]
@MonicaisHer I have upgraded to centos8, when exec `snap install edgexfoundry --edge` I got:
```
failed with exit status 1: Job for snap.edgexfoundry.kong-daemon.service failed because a timeout was exceeded.
See "systemctl status snap.edgexfoundry.kong-daemon.service" and "journalctl -xe" for details.
```
```
 [root@localhost ~]# systemctl status snap.edgexfoundry.kong-daemon.service
Unit snap.edgexfoundry.kong-daemon.service could not be found.
```

**Comment by MonicaisHer** [comment]
> @MonicaisHer I used `nexus3.edgexfoundry.org:10004/edgex-ui:latest` which will be built and updated everytime when one PR is merged. Also I just test it with source code, I still not encounter the message popup when ruleengine service is down.
> 
> are you sure you saw the popup message when navigating to ruleengine not other module page? the dashboard and app service module page will still popup error message if all the services of edgex is down, because dashboard and app service is not a real service of edgex.

Thanks for your explanation. You are right. I confirm that these popup messages came from the dashboard and app service, but not the Kuiper service.

**Comment by MonicaisHer** [comment]
> @MonicaisHer I have upgraded to centos8, when exec `snap install edgexfoundry --edge` I got:
> 
> ```
> failed with exit status 1: Job for snap.edgexfoundry.kong-daemon.service failed because a timeout was exceeded.
> See "systemctl status snap.edgexfoundry.kong-daemon.service" and "journalctl -xe" for details.
> ```
> 
> ```
>  [root@localhost ~]# systemctl status snap.edgexfoundry.kong-daemon.service
> Unit snap.edgexfoundry.kong-daemon.service could not be found.
> ```

Maybe there are some processes are using kong service's ports at the same time?

**Comment by badboy-huaqiao** [comment]
> > @MonicaisHer I have upgraded to centos8, when exec `snap install edgexfoundry --edge` I got:
> > ```
> > failed with exit status 1: Job for snap.edgexfoundry.kong-daemon.service failed because a timeout was exceeded.
> > See "systemctl status snap.edgexfoundry.kong-daemon.service" and "journalctl -xe" for details.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >  [root@localhost ~]# systemctl status snap.edgexfoundry.kong-daemon.service
> > Unit snap.edgexfoundry.kong-daemon.service could not be found.
> > ```
> 
> Maybe there are some processes are using kong service's ports at the same time?

I create  a new virtual machine with clean environment, just ran into this error after executing the install command，and it takes a long time for install operation. but it's ok, we have achieved the reason about why popup message exist.

**Comment by farshidtz** [comment]
@badboy-huaqiao I still get errors on Dashboard tab when support notification and support scheduler aren't running.

IMO, it is okay to get errors, but the error messages should be at least meaningful.

This doesn't help the user to understand what is the issue:
> code: undefined , message: An invalid response was received from the upstream server

This is shown in the console only:
> :4000/support-scheduler/api/v2/interval/all?offset=0&limit=-1:1          Failed to load resource: the server responded with a status of 502 (Bad Gateway)

**Comment by badboy-huaqiao** [comment]
@farshidtz great thanks for your feedback, the reason was mentioned above,  the dashboard module includes all other microservices instead of a signle service, the same as app service module, and I'm going to redesign both of them so that no popup message showing when relevant service down. by the way, this issue was closed, you can create a new issue with your suggestion above.
