### ISSUE TITLE
Simplify the login process 

### ISSUE THREAD

**Issue by charithmadhuranga** [edgexfoundry/edgex-ui-go#485]
issue- current method to login to the edgex secured ui  is not user friendly. (user have to interact with the proxy gateway manualy to  create a user and obtain a token and grant the access)
expectation - given the user  to configure the user account through the ui when first login(using the api of secure services )

**Comment by badboy-huaqiao** [comment]
@charithmadhuranga Hi, sorry for late reply, it's a good question, to be honest, we did do that at the begining of the GUI, but we removed it because Edgex team decided that it was unsafe to let the GUI manage users, Edgex itself does not have an open interface that can let GUI remotely obtain authentication tokens, this feature may be implemented again in a future release.

**Comment by charithmadhuranga** [comment]
If the above method is insecure it will be nice to have a proper methodology for authorization and authentication inside edgex micro services or support for opensource solutions like keycloak or hashicorp boundary.which will enhanced the user experience and give developers to options to work with user management

**Comment by badboy-huaqiao** [comment]
@lenny-intel @bnevis-i, maybe they can give you a better solution

**Comment by bnevis-i** [comment]
BTW: I am totally for having the EdgeX UI supporting OpenID connect as a login method.  That would allow users to bring their own Keycloak server and integrate it with EdgeX.  Boundary falls more into the privileged access management bucket, and I don't think we should integrate such a tool, but if there is an API that EdgeX could implement that would allow it to easily integrate with a number of PAM solutions I would like to see an enhancement proposal for it.

**Comment by lingdujunshang** [comment]
by the way , i make build edgex-ui-go (not docker or snap),how can i login ? what to make the pub-key or sec-key?where the document or what command should i use??,,,i just can not under stand ...

**Comment by badboy-huaqiao** [comment]
@lingdujunshang Hi, here [creating-access-token-for-api-gateway-authentication](https://docs.edgexfoundry.org/2.2/security/Ch-APIGateway/#creating-access-token-for-api-gateway-authentication) will show you how get it

**Comment by badboy-huaqiao** [comment]
@lingdujunshang  if you want GUI running under insecure mode, set one environment variable `export EDGEX_SECURITY_SECRET_STORE=false`
