### ISSUE TITLE
Scheduler edit RequestBody is empty

### ISSUE THREAD

**Issue by jiechenjiester** [edgexfoundry/edgex-ui-go#494]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
Scheduler

### Is this a regression?
no

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
![未标题-1](https://user-images.githubusercontent.com/59988289/151126931-19921676-7d4c-486c-b7fa-18e7f1c9b97a.jpg)

1.Add Interval Action.
2.Click CommandServiceTemplate
2.Input Path and RequestBody
3.Submit
4.Edit record
5.The RequestBody is empty.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:make run app-sample**

**EdgeX Version [**REQUIRED**]:2.1**

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
transfer this issue to edgex-ui-go, because there is no `RequestBody` in IntervalAction.  It should be `Content`
https://github.com/edgexfoundry/go-mod-core-contracts/blob/5d87b2f966db113d6ca9721a778849f7608cccf2/dtos/intervalaction.go#L20

**Comment by badboy-huaqiao** [comment]
@cloudxxx8 assign it to me, and @JamesKButcher  thanks for your feedback, I will fix it

**Comment by badboy-huaqiao** [comment]
I have just finished the updates of interval action adding or editing features, now the content is one property of interval action, which will give GUI high challenge, I redesign it, only coreDataTemplate and CommandServiceTemplate don't need user to set the value of content, which will be assembled automactically by GUI backend. 

and @cloudxxx8 what do you think? I will push my PR if you think it's ok.

see the screenshot below:
<img width="1340" alt="图片" src="https://user-images.githubusercontent.com/16172215/153415607-7f34dab3-d8b8-4606-b1fe-b5a71fe46646.png">
<img width="1329" alt="图片" src="https://user-images.githubusercontent.com/16172215/153416171-e51503e2-2e67-402c-990e-b5367e5b5815.png">

**Comment by cloudxxx8** [comment]
I thought we should hardcode to force the user to use the customer template for IntervalAction content.  This field is free-style, and could be a plain text

**Comment by badboy-huaqiao** [comment]
@cloudxxx8 yeah, I agree with you, hardcode is a better and simple way, but if we supply alternative ways is also a good way, let's think about users need to send content to command service, they need to call  some APIs to know what the path and parameters of one API of command by hand with another tools, such as Postman, but if we supply a command template to help users getting the path and parameters of one command API, it will give a bettter user experience, it's same as to core  data service's API.

**Comment by cloudxxx8** [comment]
Got it.  you are right.
I didn't notice users might send Command through Scheduler.
