### ISSUE TITLE
RuleEngine stream bug

### ISSUE THREAD

**Issue by jiechenjiester** [edgexfoundry/edgex-ui-go#495]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: RuleEngine

### Is this a regression?
no

### Description and Minimal Reproduction [**REQUIRED**]
![未标题-1](https://user-images.githubusercontent.com/59988289/151101350-42595905-eb99-4477-ba06-59424587cb61.jpg)

Bug one:
1.EdgexStream is exist.Edit it.
2.Rename EdgexStream to EdgexStream1.
3.Submit
4.The Stream is show two DATASOURCE

Bug two:
1.Delete EdgexStream1.
2.Confirm.
3.The EdgexStream is delete,the EdgexStream1 is exist.Edit.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:make run app-sample**

**EdgeX Version [**REQUIRED**]:2.1**

**Anything else relevant?**

**Comment by badboy-huaqiao** [comment]
@jiechenjiester thanks for your feedback, there are also two issues about ruleengine, see #413 ,  I'm working on refactoring the whole ruleengine module on GUI, will be done in next week, @lenny-intel assgin it to me.

**Comment by badboy-huaqiao** [comment]
@jiechenjiester I got the same errors after the testing work,  the same goes for Postman tools with calling the api of ekuiper directly following the docs of ekuiper, but I'm not so clear with their APIs, I will discuss it with the ekuiper team and get back to you next Monday

**Comment by badboy-huaqiao** [comment]
@jiechenjiester Hi, I have just discussed with kuiper team, this is indeed a bug of kuiper when updating one stream, not supporting stream's name updates, they have created a new issue for fixing work, please move to [here](https://github.com/lf-edge/ekuiper/issues/1182#issue-1145366086), deleting operation of rule stream on EdgeX GUI indeed has a problem, will be fixed after redesign

**Comment by badboy-huaqiao** [comment]
see PR-#502, it's done!
