### ISSUE TITLE
[Bug]: No effect after setting "Name" and "Description" of the device in the EdgeX UI

### ISSUE THREAD

**Issue by dlod-openvino** [edgexfoundry/edgex-ui-go#504]
#### Platform:
+ Ubuntu 20.04.4 LTS
+ EdgeX Version: 2.1
EdgeX contrainers like below
![EdgeX contrainers](https://user-images.githubusercontent.com/59691336/158926236-1e49c2b3-9c4b-47f4-b3ea-9298688c2bec.png)

#### Steps to reproduce the behavior
Step1：In the EdgeX Console, Goto "**Metadata**", in the "**Device List**" page, Select one device, and click the "**Edit**"Button
![click Edit Button](https://user-images.githubusercontent.com/59691336/158926140-7110def0-90d6-40f0-a508-e2e5510a34dd.png)

Step2: In the "**Edit Device**" page, change the "**DeviceName**" and "**Description**", after then click the "**Save**"Button
![Change the name and description](https://user-images.githubusercontent.com/59691336/158926284-52024eca-caf8-4b20-a455-6f438dfa8deb.png)

Step3: After clicking the "**Save**"Button, You will got the msg "update device success! name:..."
![save_msg](https://user-images.githubusercontent.com/59691336/158926309-8305049e-b2b1-45f3-8c51-e2ffab8473c2.png)

Step4: refresh the EdgeX Console, in the  "**Device List**" page, there is NO change in the "**Name**" and "**Description**"
![No Change](https://user-images.githubusercontent.com/59691336/158926443-0dcec1ac-4672-4c38-988e-489b108629aa.png)

**Comment by badboy-huaqiao** [comment]
see PR-#506,  done!
