### ISSUE TITLE
DeviceName update fails on EdgeX UI

### ISSUE THREAD

**Issue by vedantvdeshpande-eaton** [edgexfoundry/edgex-ui-go#521]
Users can update many primary device parameters in core metadata using the EdgeX UI. One of the writable parameters on Edgex UI is 'DeviceName,' which represents the device name. See the illustration below:

![image](https://user-images.githubusercontent.com/96241374/166703789-b6eaa8df-cb1b-43b2-9ed9-f31f88644615.png)

I attempted to make a change to the DeviceName. The success message appeared on the EdgeX UI as well. The name, however, remained unchanged after reloading the page. For more information, please see the image attached below:

![image](https://user-images.githubusercontent.com/96241374/166708362-a9348afa-57ee-473b-896b-8cd6395fb370.png)

Does EdgeX support the device name update in run-time? If this is not the case, the 'DeviceName' parameter should be read-only.

**Comment by badboy-huaqiao** [comment]
@vedantvdeshpande-eaton duplicate with  issue #504, it had been fixed.

**Comment by vedantvdeshpande-eaton** [comment]
Thanks for the quick reply. @badboy-huaqiao 
I was using an older version of the EdgeX UI.
I'll close this issue.
