### ISSUE TITLE
Support for env overrides of configuration.toml

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/edgex-ui-go#530]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
edgex-ui

### Description [**REQUIRED**]
Allow the user to specify environment variables that override values set inside configuration.toml. This will allow users to deploy UI using custom settings easier than volume mounting a whole new configuration.toml.

### Describe the solution you'd like
Env overrides work in the same manner as other EdgeX services.

### Describe alternatives you've considered
volume mounting a whole new configuration.toml

**Comment by badboy-huaqiao** [comment]
yes,  I'm planing to use go-mod-bootstrap instead of current custom implementation, assign it to me.
