### ISSUE TITLE
Add protocol template for device-onvif-camera

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/edgex-ui-go#531]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
edgex-ui

### Description [**REQUIRED**]
Add a protocol properties template for the `device-onvif-camera` service.

```
Protocol Name: Onvif
Fields:
- Address
- Port
- MACAddres
```

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
Manually entering the field names and values on the custom protocol tab

**Comment by badboy-huaqiao** [comment]
ok, assign it to me.
