### ISSUE TITLE
How to do video stream with Edgex?

### ISSUE THREAD

**Issue by prateekgml** [edgexfoundry/edgex-ui-go#540]
Hi,

I am looking for a tutorial with a video streaming use case.
My goal is to use my mobile or webcam for the video stream, pass the video stream to my object detection AI model and then export the predicted data to Edgex.

Please share any links or steps to do for this purpose.

**Comment by badboy-huaqiao** [comment]
@prateekgml we have made a sample and guide of AI+EdgeX, but it's only written by Chinese, so where are you from? can you read Chinese guide?

**Comment by badboy-huaqiao** [comment]
there is a relevant topic may help you,  please move to  [app-functions-sdk-go-issues-1148](https://github.com/edgexfoundry/app-functions-sdk-go/issues/1148)

**Comment by prateekgml** [comment]
> @prateekgml we have made a sample and guide of AI+EdgeX, but it's only written by Chinese, so where are you from? can you read Chinese guide?

Yes, I can, please share that guide.

**Comment by badboy-huaqiao** [comment]
@prateekgml https://mp.weixin.qq.com/s/Prs3WdlWMo3Ch61cM-j6kw

**Comment by prateekgml** [comment]
> @prateekgml https://mp.weixin.qq.com/s/Prs3WdlWMo3Ch61cM-j6kw

It seems the link cannot be opened outside China.

**Comment by badboy-huaqiao** [comment]
@prateekgml you're not in China?  there's no other link, maybe we can post that guide on Github, but it would take some  time.
there is another guide provided by Intel, but I'm not familiar with it and not test it yet, maybe it will be helpful to you, see here https://www.intel.com/content/www/us/en/developer/articles/technical/video-analytics-service.html?wapkw=EVAM

**Comment by lenny-intel** [comment]
The new Camera Management App Service example demonstrates how to do this using Intel's EVAM and the new ONVIF camera service. 
https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/camera-management

Note the new camera service hasn't been released yet but is available from `nexus3.edgexfoundry.org:10004/device-onvif-camera`

**Comment by prateekgml** [comment]
@lenny-intel thanks for sharing. It will be really helpful.
