### ISSUE TITLE
Replace use of gopkg.in/mgo.v2/bson with github.com/google/uuid

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-ui-go#541]
Code [here ](https://github.com/edgexfoundry/edgex-ui-go/blob/49cc9d365f5a5b30fcf0107d6b34acf483ef27cd/internal/domain/user.go#L21) uses gopkg.in/mgo.v2/bson for User Id.

The rest of Edgex and other portions of the UI are using github.com/google/uuid for IDs.

This code should also use github.com/google/uuid  to remove dependency on gopkg.in/mgo.v2/bson

**Comment by badboy-huaqiao** [comment]
@lenny-intel that's legacy code which is not used anymore, would be removed at some time,  I will refactor the GUI backend

**Comment by lenny-intel** [comment]
Ok, sounds good.
