### ISSUE TITLE
Attribution.txt and LICENSE files not copied into Docker image or snap

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-ui-go#543]
Attribution.txt and LICENSE files must be part of the released artifact.
They need to be copied into the Docker image and snap similar to here:
https://github.com/edgexfoundry/app-service-configurable/blob/main/Dockerfile#L46-L47
and here
https://github.com/edgexfoundry/app-service-configurable/blob/main/snap/snapcraft.yaml#L81-L84

**Comment by lenny-intel** [comment]
@farshidtz , FYI on the snap part of this.

**Comment by cloudxxx8** [comment]
@badboy-huaqiao may we resolve this issue by the code freeze date (Oct-26th)?

**Comment by badboy-huaqiao** [comment]
@cloudxxx8 done, please review the related PR
