### ISSUE TITLE
Add Provision Watchers tab to Metadata

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-ui-go#548]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 Metadata section

### Description [**REQUIRED**]
 Core Metadata has Provision Watchers APIs similar to the others for Add, Update and Delete

### Describe the solution you'd like
 Add tab under the Metadata section for Provision Watchers

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by badboy-huaqiao** [comment]
ok, that's coming soon.

**Comment by A808597949** [comment]
You can now add and view existing provision watchers, and the editing and deletion functionalities are coming soon.

**Comment by A808597949** [comment]
I have completed the basic functionality of the provision watcher in my fork wei.jin branch.

**Comment by A808597949** [comment]
#625

**Comment by A808597949** [comment]
complete in #625

**Comment by jumpingliu** [comment]
Closed #548 as completed via #630
