### ISSUE TITLE
[UI] "how to get access token" link incorrect on main

### ISSUE THREAD

**Issue by dovholuknf** [edgexfoundry/edgex-ui-go#604]
# 🐞 Bug Report

### Affected Services egex-ui-go login
when security is enabled and opening the UI you'll see:
![image](https://user-images.githubusercontent.com/46322585/236270702-1e04b322-490d-4984-b414-f34870ffe6e9.png)

The main branch of edgex-ui-go, when clicking this "How to get access token" doc link, you're sent to (notice the 2.1):

https://docs.edgexfoundry.org/2.1/security/Ch-APIGateway/#creating-access-token-for-api-gateway-authentication

It should be some kind of 3.0 link

### Is this a regression?

yes? no? it's a major version change, hard to call that a regression

### Description and Minimal Reproduction [**REQUIRED**]

* clone the repo
* start the dependant services in SECURE mode = true
* run the ui
* get the login screen click that link

**Comment by cloudxxx8** [comment]
the link should be updated to 3.0
https://docs.edgexfoundry.org/3.0/security/Ch-APIGateway/#creating-access-token-for-api-gateway-authentication

If possible, there should be a version variable for that, like
https://docs.edgexfoundry.org/{{ version }}/security/Ch-APIGateway/#creating-access-token-for-api-gateway-authentication

**Comment by jumpingliu** [comment]
This issue has been verified by running edgex-UI on localhost and "How to get access token" does point to 

[https://docs.edgexfoundry.org/3.0/security/Ch-Authenticating/#how-to-make-authenticated-edgex-calls](https://docs.edgexfoundry.org/3.0/security/Ch-Authenticating/#how-to-make-authenticated-edgex-calls)

**Comment by lenny-intel** [comment]
I also have confirmed it is now corrected. Closing issue as fixed
