### ISSUE TITLE
Routes in router.go error edgex-ui-go

### ISSUE THREAD

**Issue by mglmc** [edgexfoundry/edgex-ui-go#624]
# 🐞 Bug Report

### Affected Services

The issue is located in edgex-ui-go profile functions call for internal/router.go that are in internal/handler/profile.go

### Is this a regression?

Yes, the previous version in which this bug was not present was 2.3 Levski

### Description and Minimal Reproduction

In compose-builder
1. make gen ui ds-rest ds-virtual
2. Run the docker compose

Steps:
1.  Open EdgeX Console UI with security
2.  Put the token
3.  Click Device Profile
4.  Select any device and click in Edit

## 🔥 Exception or Error
<pre><code>
Example:

When the request is sent
For V2.3 -> http://localhost:4000/api/v2/profile/yaml/name/Random-Boolean-Device
For V3.0 -> EdgeX: http://localhost:4000/api/v3/profile/yaml/name/Random-Boolean-Device

Good case with 2.3 Levski:
Response 200 OK
Bad case with 3.0 Minnesota:
ERROR Backend returned code 404, body was: undefined
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**  ui ds-rest ds-virtual

**EdgeX Version:** 3.0

**Anything else relevant?**
When try any path defined in router.go except /api/v3/pin and /api/v3/auth/securemode it seems that there is an error during the process of getting the Consul Token (getAclTokenOfConsul) and it _says unable to get consul acl token_.

All the calls that are not using the Application Service SDK seems that are working fine.

**Comment by lenny-intel** [comment]
I have recreated (confirmed) this bug.

**Comment by A808597949** [comment]
> I have recreated (confirmed) this bug.

After testing, I found that the 'jwtSecretProvider := secret.NewJWTSecretProvider(bootstrapContainer.SecretProviderExtFrom(rh.dic.Get))' in the 'handler/profile' file did not yield the expected results, leading to an error. This function is located in "github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/secret", perhaps a solution can be found there.

**Comment by cloudxxx8** [comment]
@A808597949 Could you please specify what is the expected value and what is the value service receiving now?
Could you please upgrade go.mod to use the latest 3.1.0-dev.x?
https://github.com/edgexfoundry/edgex-ui-go/blob/f65144e2eab94398f5e1f661bab73f031313c3c8/go.mod#L6-L10

**Comment by lenny-intel** [comment]
This issue is resolved by #645
