### ISSUE TITLE
Get Button Url bug

### ISSUE THREAD

**Issue by Pluviophile225** [edgexfoundry/edgex-ui-go#626]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 

The Button "Get" on the Command List
When I click the "Get" Button, It goes to url like:http://localhost:4000/core-command/api/v3/device/name/Random-UnsignedInteger-Device/Uint16?ds-pushevent=yes&ds-returnevent=yes.
And When I type the url in Chrome, and change yes to true, It goes right.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
just need to click the get button

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
3.0

**Anything else relevant?**

**Comment by mglmc** [comment]
Confirmed, I have the solution, during the morning I'm going to open the PR to fix this issue :)

**Comment by A808597949** [comment]
I am an official representative, and I will be following up on this issue. I apologize for the delayed response and sincerely appreciate your contribution and suggestions.
