### ISSUE TITLE
Error in the request of a service configuration in the UI

### ISSUE THREAD

**Issue by mglmc** [edgexfoundry/edgex-ui-go#628]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
version affected: 3.0
device service: edgex-ui-go 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 2.3

### Description and Minimal Reproduction
When there is a request to get the configuration of a device service, the request failed.
The request is http://localhost:4000/api/v3/registrycenter/config/XXXXX

## 🔥 Exception or Error
Error in the current version
In the example given is: http://localhost:4000/api/v3/registrycenter/config/app-rules-engine
With the response ERROR Backend returned code 404, body was: undefined

![Screenshot 2023-08-04 124434](https://github.com/edgexfoundry/edgex-ui-go/assets/20265876/3ce52854-bb2b-407f-b873-57d4e33abe8f)

## 🌍  Your Environment
**Deployment Environment:**
make gen ui ds-virtual
And test it doing the manual click in the UI or doing curl http://localhost:4200/api/v3/registrycenter/config/{service required}

**EdgeX Version:** 3.0

**Anything else relevant?**

**Comment by A808597949** [comment]
Got it! It looks like you've already resolved the issue.

**Comment by mglmc** [comment]
Yes @A808597949, It is just waiting to be reviewed next to the https://github.com/edgexfoundry/edgex-ui-go/pull/627
