### ISSUE TITLE
Unauthorized on Add Profile

### ISSUE THREAD

**Issue by mijjjj** [edgexfoundry/edgex-ui-go#631]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

edgeX-UI

### Description and Minimal Reproduction [**REQUIRED**]

I want to add a device meta-information for modbus after I log in to the UI with a token, but it shows no permission when I submit it. I don’t know how to grant this permission, or this may be a bug.

## 🔥 Exception or Error
![image](https://github.com/edgexfoundry/edgex-ui-go/assets/37797122/b4c87c56-68bb-4509-a3d4-c95792463d71)

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

docker

**EdgeX Version [**REQUIRED**]:**

3.0.0

**Anything else relevant?**

**Comment by jiekechoo** [comment]
@mijjjj Yes, it was a bug in secure mode, see #624 . You could pull the latest commit, and enable `SecretStore` in docker-compose refer https://github.com/yiqisoft/edgex-compose/tree/feature-edgex-ui

**Comment by jiekechoo** [comment]
@lenny-intel This issue is the same as #624.

**Comment by lenny-intel** [comment]
@jiekechoo , @mijjjj , With @bnevis-i 's help we have determined the appropriate fix for this issue. See #666

**Comment by jiekechoo** [comment]
@lenny-intel Thanks for your help. Rencently, I wanted to add request `Authorization` header to `NewDeviceProfileClient` params, but can't find the solution.
