### ISSUE TITLE
When accessing the AppService menu, an error occurs: "Oops!!! registry center service is unavailable!"

### ISSUE THREAD

**Issue by zzlovelp** [edgexfoundry/edgex-ui-go#672]
![1700643437755](https://github.com/edgexfoundry/edgex-ui-go/assets/151725969/1c205c92-7052-45ba-945d-913e0acb73c0)

**Comment by zzlovelp** [comment]
I used edgex-compose 3.1.0, When accessing /api/v3/registrycenter/ping, it returns a code 500，‘unable to get consul acl token'.

**Comment by lenny-intel** [comment]
@zzlovelp , I have recreated this issue when running in secure mode. Do you need secure mode? If not then run the edgex stack using the non-secure docker compose file here:
https://github.com/edgexfoundry/edgex-compose/blob/v3.1/docker-compose-no-secty.yml

**Comment by lenny-intel** [comment]
Per discussion with @bnevis-i , the solution is to have the UI prompt the user for the Consul ACL token similar to the JWT Token so  it can be add to any direct calls to Consul.

**Comment by bnevis-i** [comment]
This is a bug that was introduced in EdgeX 3.0.  In EdgeX 2.x, we used to configure Kong to respond to the /consul API at the API gateway by injecting the consul token into the backed request.  In EdgeX 3.0, with the new nginx api gateway, we don't have a programmatic API to insert the consul token.  Thus the edgex-ui-go needs to be changed to know what the consul token is when it makes the request.

https://github.com/edgexfoundry/edgex-ui-go/blob/926a50b7407512a6b860808b199c72c47dd05976/internal/handler/registercenter.go#L79

and

https://github.com/edgexfoundry/edgex-ui-go/blob/926a50b7407512a6b860808b199c72c47dd05976/internal/handler/registercenter.go#L103

and

https://github.com/edgexfoundry/edgex-ui-go/blob/926a50b7407512a6b860808b199c72c47dd05976/internal/router.go#L42

**Comment by dovholuknf** [comment]
If it's acceptable, I have a workable solution by adding a second field to the login screen. It'll effectively look like this:
![image](https://github.com/edgexfoundry/edgex-ui-go/assets/46322585/e558cd8e-2448-432d-9b92-6fc8ac624f8c)

If you supply both the Token and Registry token, the AppService will be usable:
![image](https://github.com/edgexfoundry/edgex-ui-go/assets/46322585/e2f7daec-e568-4c5a-b93d-0ede177dd73d)

I wanted to get this working for the upcoming OpenZiti integration. I can put a PR up if that seems acceptable?

**Comment by lenny-intel** [comment]
Yes!!!, with minor changes:

1. Token => Secret Store Token
2. Registry Token => ACL Token

**Comment by dovholuknf** [comment]
No problem. I have no idea how to check the internationalization of it so hopefully someone else can help there and english "only" will be fine. Revised screen:

![image](https://github.com/edgexfoundry/edgex-ui-go/assets/46322585/009bbae5-3dc2-4411-8824-09fca4c00e2b)

Will it be acceptable to submit this fix as part of the OpenZiti work?

**Comment by lenny-intel** [comment]
Nope, please do it in separate PR.

**Comment by dovholuknf** [comment]
PR put up that addresses this https://github.com/edgexfoundry/edgex-ui-go/pull/700/files
