### ISSUE TITLE
command set returns failed  

### ISSUE THREAD

**Issue by caocaocaodou** [edgexfoundry/edgex-ui-go#71]
excuse me
when i send the set command to device-simple it  returns failed although the switch state is changed.
at first the device-simple debug error, so i  changed device.js  sendCommand  data: from JSON.stringify(paramBody),  to  "["+JSON.stringify(paramBody)+"]",

am i right ?  is there anything wrong?
thank you!

**Comment by badboy-huaqiao** [comment]
@caocaocaodou didn't it work after you changed ? if it works , you can submit your code, thanks.

**Comment by caocaocaodou** [comment]
actually the state of the switch is changed from true to false, but the “Reading Value” shows “failed” not “success”
so i want to know why 
what's the problem ?  is there anything wrong although it works？
thank you！

**Comment by gaofeng3695** [comment]
@badboy-huaqiao @caocaocaodou

**Comment by gaofeng3695** [comment]
@caocaocaodou @badboy-huaqiao 

i have fixed  it, the PR-#72

**Comment by badboy-huaqiao** [comment]
@gaofeng3695  good catch ! @caocaocaodou you can update your local code and try it again, if it works well , i will close this issue. thanks!

**Comment by badboy-huaqiao** [comment]
it has been solved，I close it now
