### ISSUE TITLE
Update to using go modules

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-ui-go#79]
EdgeX go-based projects now use go modules rather than glide for dependency management

**Comment by badboy-huaqiao** [comment]
@anonymouse64 ok，assign it to me

**Comment by anonymouse64** [comment]
@badboy-huaqiao I don't have permission to assign issues for this repository unfortunately

**Comment by badboy-huaqiao** [comment]
@anonymouse64 ok，I assign it to myself😁

**Comment by anonymouse64** [comment]
As mentioned on the [PR](https://github.com/edgexfoundry/edgex-ui-go/pull/83), associated with this change to using go modules, we need to remove `glide install` from the `prepare` target in the Makefile. We can't entirely remove the prepare target, as it's still necessary for building both the master and delhi branches from jenkins, and the delhi branch still will use glide.

**Comment by badboy-huaqiao** [comment]
@anonymouse64 ok, thanks for your reminder, i will fix it on the next PR.

**Comment by badboy-huaqiao** [comment]
I have finished it , close it now
