### ISSUE TITLE
Use configuration.toml for handling configuration items at runtime

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-ui-go#80]
All of the configuration constants enumerated in 

https://github.com/edgexfoundry/edgex-ui-go/blob/069e2f7b09e6aa21fff501d1fe7551c686994b34/configs/const.go#L9-L37

should instead be configurable at runtime, such as the desired port number, the paths for routes, etc.

Additionally, things like the project root for where to find the web app static path and such should also be configurable through a configuration.toml file, i.e. this variable:

https://github.com/edgexfoundry/edgex-ui-go/blob/069e2f7b09e6aa21fff501d1fe7551c686994b34/web/app/common/filter.go#L33

should be configurable at runtime

**Comment by badboy-huaqiao** [comment]
ok, i will refactor it

**Comment by badboy-huaqiao** [comment]
@anonymouse64 i think i should move the static folder under cmd folder path ,what do you think?

**Comment by badboy-huaqiao** [comment]
The current project tree structure is designed by anther contributor who had left long time ago, i and other contributor do not agree with current project tree structure, especially when serving static resources, it needs to span multiple paths.

**Comment by anonymouse64** [comment]
@badboy-huaqiao I think that the location of those files should be configurable, so that you can specify the location of those files from the command line. 

Alternatively to putting static inside `cmd`, I would propose the following structure initially:
```
$ tree  -d -I vendor
.
├── api
├── app
│   ├── common
│   ├── component
│   ├── controller
│   ├── domain
│   ├── repository
│   │   ├── mm
│   │   └── mongo
│   └── service
├── assets
│   └── images
├── bin
├── cmd
│   └── edgex-ui-go
│       └── res
├── configs
├── deployments
├── docker-file
├── docs
├── initial
├── static
│   ├── css
│   │   └── devices
│   ├── data
│   ├── js
│   │   └── pages
│   │       └── devices
│   ├── pages
│   │   └── devices
│   └── vendors
│       ├── bootstrap
│       │   ├── css
│       │   └── js
│       ├── echarts
│       │   └── theme
│       ├── font-awesome-4.7.0
│       │   ├── css
│       │   ├── fonts
│       │   ├── less
│       │   └── scss
│       └── jquery
└── templates

50 directories
```

Where specifically, 
* `configuration.toml` lives at `/cmd/edgex-ui-go/res/configuration.toml`
* `/web/app` is moved to `/app`
* `/web/templates is moved to `/templates` 
* `/web/static` is moved to `/static`

**Comment by badboy-huaqiao** [comment]
@anonymouse64 ok, it looks properly, i will refactor it follow your proposal

**Comment by badboy-huaqiao** [comment]
I have finished it , close it now
