### ISSUE TITLE
Docker image shouldn't contain source code from git repository

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-ui-go#82]
The dockerfile for this project should only include compiled binaries and static configuration/data files such as the `web/static` and `web/template` directories. This line seems to be the problem:

https://github.com/edgexfoundry/edgex-ui-go/blob/069e2f7b09e6aa21fff501d1fe7551c686994b34/docker-file/Dockerfile#L22

which copies all of the repository into the image. Instead, something like for edgex-go should be done where just the binaries are copied into the image:

https://github.com/edgexfoundry/edgex-go/blob/78ba8bd0017a61459c0f8cd4eb25efb4f917d6ab/cmd/core-data/Dockerfile#L43-L45

**Comment by badboy-huaqiao** [comment]
ok，assign it to me

**Comment by badboy-huaqiao** [comment]
I have finished it , see [PR-#91](https://github.com/edgexfoundry/edgex-ui-go/pull/91)
